ENGRAID = [
    "PUSSYBOY",
    "DICK HAIR",
    "MOM'S PUBES",
    "MOTHERFUCKER",
    "YOUR MOM'S CUNT",
    "DICK BALLS",
    "MOSQUITO PUBES",
    "SLAP YOUR MOM'S CUNT?",
    "YOUR MOM'S LOOSE PUSSY",
    "YOUR SIS BIGGEST WHORE",
    "YOUR MOM EVEN BIGGER RANDI",
    "YOUR DAD'S A CUCK",
    "HOW MUCH I FUCK YOUR MOM NOW",
    "WE FUCKED YOUR MOM",
    "I'LL MAKE REELS WITH YOUR MOM ON ROAD",
    "YOUR MOM'S CUNT IS TOP SEXY",
    "WANNA KNOW HOW I SLAP YOUR MOM'S CUNT",
    "YOU'LL TYPE ON MY DICK",
    "CATCH SPEED DICKHEAD",
    "MATCH DAD'S SPEED",
    "DICKHEAAAD",
    "CAN'T MATCH DAD'S SPEED?",
    "HEY HEY MY KID",
    "GOT FUCKED BY DAD",
    "DIG THE FARMER MORE?",
    "I'LL RAPE YOU BITCH",
    "HAHAHAAAA",
    "KIDSSSS",
    "YOUR MOM GOT FUCKED, DON'T RUN",
    "DICK FROM DAD",
    "KIDS RUNNING HAHAHA",
    "SISTERFUCKER SHAME",
    "HOW MANY ABUSES FOR YOUR MOM",
    "BASTARD",
    "SHAME ON YOU",
    "MY DICK BALLS",
    "HOW MANY ABUSES FOR YOUR MOM SIS",
    "WHORE'S SONNNN",
    "KIDSSSSSS",
    "SHOVE FIST IN YOUR ASS",
    "SUCK MY DICK",
    "GO SUCK YOUR MOM",
    "SISTER'S DICK",
    "SISTER'S BALLS",
    "YOUR FAMILY'S TURN TO GET FUCKED",
    "SON YOUR MOM BIGGEST RANDI",
    "DICK HAIR PISS",
    "YOU'RE BONDAGE ON MY DICK",
    "WISH I JERKED AND SLEPT, YOU WOULDN'T BE BORN",
    "MISTAKE MAKING YOU",
    "CATCH SPEEEDD",
    "SHOVE MY DICK IN YOUR ASS",
    "BAMBOO IN YOUR ASSS",
    "ASS TORN KID",
    "BIG BALLS STILL UNDER DICK",
    "THOUSAND DICKS IN YOUR ASS",
    "PUBE PISS",
    "YOUR MOM'S BLACK CUNT",
    "DONKEY'S SON",
    "DOG'S OFFSPRING",
    "DOG BREED",
    "DOG BALLS",
    "YOUR MOM'S CUNT, YOUR MOM RANDIIIIII",
    "DICK HAIR",
    "TAKE IT IN MOUTH",
    "DICK SWEAT",
    "MY DICK BALLS",
    "HAHAHAAAAAA",
    "GOT FUCKEDDD",
    "WHOREHOUSE KID",
    "MARRIED ASS",
    "DOG DICK IN YOUR ASS",
    "YOUR MOM'S PUSSY",
    "YOUR MOM'S CUNT",
    "WORMS IN YOUR ASS",
    "OWL'S KID",
    "LISTEN MOTHERFUCKER",
    "YOUR MOM'S PUSSY",
    "SISTER'S DICK",
    "YOUR MOM'S CUNT CHUTNEY",
    "TAKE MY DICK IF YOU WANT",
    "FAGGOT",
    "IDIOT",
    "I'LL DRIVE JCB ON YOUR MOM'S CUNT",
    "UNDERSTAND DICKHEAD",
    "OR SLAP YOUR ASS",
    "YOUR SIS TAKES MINE DAILY",
    "MADE MMS WITH YOUR GF 😂",
    "YOU IDIOT, YOUR FAMILY IDIOT",
    "HOW MUCH MORE, I'M FULL 😂",
    "I'LL WRITE ABCD IN YOUR MOM'S CUNT",
    "I'LL RUN WITH YOUR MOM",
    "RANDIII",
    "KIDDD",
    "I'LL FUCK",
    "RANDI",
    "RANDI'S PUP",
    "SEND YOUR MOMMM",
    "I'M YOUR DAD",
    "I'LL STICK HAND IN YOUR MOM'S CUNT AND RUN",
    "I'LL LAY YOUR MOM ON ROAD",
    "I'LL SELL YOUR MOM ON GB ROAD",
    "BLACK MITCH IN YOUR MOM'S CUNT",
    "YOUR MOM CHEAP RANDI",
    "I'LL PUT PIGEON IN YOUR MOM'S CUNT MAKE SOUP MADARCHOD",
    "YOUR MOM RANDI",
    "I'LL POUR DETOL IN YOUR MOM'S CUNT MADARCHOD",
    "YOUR MOM'S PUSSY",
    "LAPTOP IN YOUR MOM'S CUNT",
    "YOUR MOM RANDI",
    "I'LL LAY YOUR MOM ON BED AND FUCK",
    "I'LL TAKE YOUR MOM TO AMERICA MADARCHOD",
    "I'LL BURST COCONUT IN YOUR MOM'S CUNT",
    "I'LL POUR DETOL IN YOUR MOM'S ASS",
    "I'LL FEED YOUR MOM HORLICKS MADARCHOD",
    "I'LL LAY YOUR MOM ON ROADDD",
    "YOUR MOM'S PUSSY",
    "HOLD MY DICK MADARCHOD",
    "SHUT UP YOUR MOM'S PUSSY",
    "YOUR MOM GOT FUCKED DICKHEAD",
    "YOUR MOM'S PUSSY",
    "MOTHERFUCKERRR",
    "YOUR MOM'S PUSSY",
    "I'LL FUCK YOUR SISTERRR MOTHERFUCKERRR",
    "GET OUT MADARCHOD",
    "RANDI'S KID",
    "YOUR MOM MY FAN",
    "YOUR SEXY SIS CUNT OPEN",
]

ENGREPLYRAID = [
    "MADARCHOD, I'LL CHEW GUTKHA AND SPIT IT RIGHT IN YOUR MOM'S PUSSY 🤣🤣",
    "I'LL STAB YOUR SISTER'S PUSSY WITH A KNIFE AND MAKE THAT SHIT BLEED",
    "DON'T YOU HAVE A SISTER? WAIT 9 MONTHS, I'LL GIVE YOU A REAL ONE 🤣🤣🤩",
    "I'LL TURN YOUR MOM'S PUSSY INTO AN AIRPORT AND FILL IT WITH FLIGHTS ✈️🛫",
    "I'LL DETONATE A SUITCASE BOMB IN YOUR MOM'S PUSSY TILL HER PUBES BURN TO ASH 💣",
    "I'LL SHOVE A WHOLE SCOOTER UP YOUR MOM'S PUSSY 👅",
    "I'LL STAB YOUR SISTER'S PUSSY WITH A KNIFE AND MAKE THAT SHIT BLEED",
    "I'LL STAB YOUR SISTER'S PUSSY WITH A KNIFE AND MAKE THAT SHIT BLEED",
    "I'LL CUT YOUR MOM'S PUSSY HAIR, FEED IT TO STREET DOGS 🦮, THEN LET THEM EAT HER OUT LIKE BREAD 🍞",
    "I'LL JERK OFF ALL OVER YOUR SISTER, UP AND DOWN 🆙🆒😙",
    "I'LL STICK MY HAND IN YOUR MOM'S PUSSY AND PULL OUT SOME KIDS 😍",
    "I'LL SHOVE BANANA PEELS IN YOUR SISTER'S PUSSY 🍌🍌😍",
    "I'LL INSTALL A USERBOT IN YOUR SISTER'S PUSSY FOR CHEAP SPAM FUCKING",
    "YOUR SISTER'S A TOTAL SLUT 😋😛",
    "I'LL INSTALL AN AC IN YOUR MOM'S PUSSY TO COOL ALL THAT HEAT DOWN",
    "I'LL MAKE YOUR SISTER DRINK HORLICKS, MADARCHOD 😚",
    "I'LL SHOVE REBAR IN YOUR MOM'S ASS, MADARCHOD, AND HANG OFF IT TO KNOCK HER UP 😱😱",
    "YOUR MOM GETS BLESSED BY JITU BHAIYA FROM KOLKATA'S DICK 🤩🤩",
    "I'M YOUR MOMMY'S FANTASY, DUDE – GO TAKE CARE OF YOUR SISTER 😈😈",
    "I WAS YOUR FIRST DAD, MADARCHOD",
    "I'LL JACK OFF TO XVIDEOS.COM INSIDE YOUR SISTER'S PUSSY 🤡😹",
    "I'LL GANGBANG YOUR MOM WITH THE WHOLE GROUP CHAT 🙌🏻☠️",
    "I'LL RAM MY DICK IN YOUR GIRL'S ASS AND PULL OUT ANOTHER ONE JUST LIKE YOU, MADARCHOD 🤘🏻🙌🏻☠️",
    "STAY IN YOUR LANE OR I'LL SHOVE A STICK UP YOUR ASS AND PULL IT OUT YOUR MOUTH – YOUR BODY WILL LOOK LIKE A FUCKING POLE 🙄🤭🤭",
    "WHILE PLAYING LUDO WITH YOUR MOMMY, I'LL SHOVE MY DICK IN HER MOUTH ☝🏻☝🏻😬",
    "I'LL SWING YOUR SISTER ON MY DICK SO HARD SHE'LL GET PREGNANT MID-SWING 👀👯",
    "I'LL STICK A BATTERY IN YOUR MOM'S PUSSY AND TURN IT INTO A POWERBANK 🔋 🔥🤩",
    "I'LL CODE C++ STRING ENCRYPTION IN YOUR MOM'S LOOSE PUSSY – THAT SHIT WILL FINALLY STOP LEAKING 😈🔥😍",
    "I'LL SHOVE A BROOM IN YOUR MOM'S ASS AND TURN HER INTO A PEACOCK 🦚 🤩🥵😱",
    "I'LL SHOULDER YOUR PUSSY IN YOUR PUSSY – IT'LL HURT EVEN WHEN YOU'RE SHAKING 😱🤮👺",
    "I'LL PUT YOUR MOM ON THE STREETS AND FUCK HER HOLES FOR CASH 💰 😵🤩",
    "YOUR MOM'S PUSSY HAS 4 HOLES, MADARCHOD – I SEALED ONE AND IT STILL LEAKS LIKE CRAZY 👊🤮🤢🤢",
    "I'LL GROW A BANYAN TREE IN YOUR SISTER'S PUSSY – EVERYONE WILL COME FOR OXYGEN DURING COVID 🤢🤩🥳",
    "I'LL RUN SUDO AND BIGSPAM IN YOUR MOM'S PUSSY AND FUCK HER 9999 TIMES 🤩🥳🔥",
    "I'LL FILL YOUR SISTER'S PUSSY WITH BESAN LADDOOS 🤩🥳🔥😈",
    "I'LL DIG YOUR MOM'S PUSSY, FIT A CYLINDER ⛽️, AND TURN IT INTO A BUTTER CHURN 🤩👊🔥",
    "I'LL SHOVE A HOOKAH IN YOUR MOM'S PUSSY AND HANG IT AT THE CROSSROADS, MADARCHOD 😈😱🤩",
    "I'LL SLIDE A CREDIT CARD IN YOUR MOM'S PUSSY AND WITHDRAW 500 RUPEE NOTES NON-STOP 💰💰🤩",
    "I'LL MAKE A PIG FUCK YOUR MOM AND SHE'LL POP OUT 6 PIGLETS AT ONCE 💰🔥😱",
    "I'LL PLUG AN APPLE 18W CHARGER IN YOUR SISTER'S PUSSY 🔥🤩",
    "I'LL PLUG A ONEPLUS WARP 30W CHARGER IN YOUR SISTER'S ASS – HIGH POWER 💥😂😎",
    "I'LL ORDER YOUR SISTER'S PUSSY ON AMAZON FOR 10 RS AND SELL IT ON FLIPKART FOR 20 🤮👿😈🤖",
    "I'LL ORDER A ZOMATO SUBWAY BFF VEG SUB COMBO [15CM, 16 INCHES] INTO YOUR MOM'S HUGE PUSSY COD, CAST A SPELL WHEN THE DELIVERY GUY ARRIVES, AND 9 MONTHS LATER SHE'LL GIVE FREE DELIVERY 🙀👍🥳🔥",
    "YOUR SISTER'S PUSSY IS BLACK 🙁🤣💥",
    "I'LL COMMIT CHANGES IN YOUR MOM'S PUSSY THEN YOUR SISTER'S WILL AUTO-UPDATE 🤖🙏🤔",
    "I'LL RUN THE ENTIRE INDIAN RAILWAY IN YOUR AUNTY'S PUSSY 🚂💥😂",
    "YOU, YOUR SISTER, YOUR WHOLE FAMILY – ALL WHORES AND SLUTS 🤢✅🔥",
    "I'LL FORM AN IONIC BOND IN YOUR SISTER'S PUSSY AND RUIN HER VIRGINITY 📚 😎🤩",
    "ASK YOUR RANDI MOM WHO FUCKED HER THAT DARK NIGHT – SHE'LL GIVE YOUR DAD'S NAME 🤩🥳😳",
    "I'LL RUN THE METRO THROUGH BOTH YOUR MOM AND YOUR PUSSY, MADARCHOD 🚇🤩😱🥶",
    "I'LL FUCK YOUR MOM SO HARD EVEN YOUR DAD WON'T RECOGNIZE HER 😂👿🤩",
    "I'LL RUN A HAIR DRYER IN YOUR SISTER'S PUSSY 💥🔥🔥",
    "I'LL OPEN A RANDI BROTHEL FULL OF TELEGRAM SLUTS IN YOUR MOM'S PUSSY 👿🤮😎",
    "I'LL STICK ALEXA IN YOUR MOM'S PUSSY AND BLAST DJ MUSIC 🎶 ⬆️🤩💥",
    "I'LL HOST MY BOT ON GITHUB INSIDE YOUR MOM'S PUSSY 🤩👊👤😍",
    "I'LL TURN YOUR SISTER INTO A VPS AND RUN 24/7 BASH FUCK COMMANDS 🤩💥🔥🔥",
    "I'LL STICK YOUR DICK IN YOUR MOMMY'S PUSSY AND CUT IT OFF, MADARCHOD 🔪😂🔥",
    "LISTEN, YOUR MOM'S PUSSY AND YOUR SISTER'S TOO 👿😎👊",
    "SEEING YOU MAKES ME HORNY FOR YOUR RANDI SISTER, BROTHERFUCKER 👿💥🤩🔥",
    "LISTEN MADARCHOD DON'T BOUNCE TOO MUCH OR I'LL FUCK YOUR MOM IN ONE MINUTE ✅🤣🔥🤩",
    "ASK YOUR MOM WHO CAME TO FUCK HER THAT DARK NIGHT! SHE'LL TAKE YOUR DAD'S NAME 😂👿😳",
    "I'LL FUCK YOUR SISTER, FILL HER PUSSY WITH DIRT AND CEMENT TO BUILD A HOUSE 🏠🤢🤩💥",
    "YOU STILL DON'T GET THAT I'M THE ONE WHO KNOCKED UP YOUR MOM – ASK THAT RANDI'S KID 🤩👊👤😍",
    "I'LL PLUG SPOTIFY IN YOUR MOM'S PUSSY AND PLAY LOFI ALL DAY 😍🎶🎶💥",
    "I'LL OPEN A NEW RANDI BROTHEL FOR YOUR MOM – DON'T WORRY 👊🤣🤣😳",
    "I'M YOUR DAD, MADARCHOD – I FUCK YOUR MOM ON THE STREETS AND DRINK BOOZE WITH THE CASH 🍷🤩🔥",
    "I'LL SHOVE MY HUGE DICK IN YOUR SISTER'S PUSSY SO HARD SHE'LL DIE OF BLACKOUT 🤩😳😳🔥",
    "I'LL SHOVE A FULL KINGFISHER BOTTLE IN YOUR MOMMY'S PUSSY AND SMASH IT INSIDE 😱😂🤩",
    "I'LL FUCK YOUR MOM SO MUCH SHE'LL REMEMBER MY FUCKING EVEN IN HER DREAMS, RANDI 🥳😍👊💥",
    "I'LL CHASE AND FUCK YOUR MOMMY AND SISTER – EVEN IF THEY DON'T SPEAK I'LL SHOVE MY DICK DEEP 😎😎🤣🔥",
    "I'LL SELL YOUR MOMMY'S PUSSY ON OLX AND USE THE MONEY TO OPEN YOUR SISTER'S BROTHEL 😎🤩😝😍",
    "I'LL FUCK YOUR MOM'S PUSSY SO HARD YOU WON'T BE ABLE TO STAY AWAY FROM THAT EPIC FUCK 😏😏🤩😍",
    "LISTEN YOU RANDI'S SON, LEARN FROM YOUR SISTER HOW TO GET ASS-FUCKED 😏🤬🔥💥",
    "I'M YOUR MOM'S LOVER AND YOUR SISTER'S LOVE – COME SUCK MY DICK 🤩🤣💥",
    "I'LL INSTALL A USERBOT IN YOUR SISTER'S PUSSY FOR CHEAP SPAM FUCKING",
    "I'LL SHOVE REBAR IN YOUR MOM'S ASS, MADARCHOD, AND HANG OFF IT TO KNOCK HER UP 😱😱",
    "I'LL STICK MY HAND IN YOUR MOM'S PUSSY AND PULL OUT SOME KIDS 😍",
    "I'LL SHOVE BANANA PEELS IN YOUR SISTER'S PUSSY 🤤🤤",
    "I'LL DETONATE A SUITCASE BOMB IN YOUR MOM'S PUSSY TILL HER PUBES BURN TO ASH 💣💋",
    "I'LL MAKE YOUR SISTER DRINK HORLICKS AND FUCK HER, MADARCHOD 😚",
    "I'LL RAM MY DICK IN YOUR GIRL'S ASS AND PULL OUT ANOTHER ONE JUST LIKE YOU, MADARCHOD 😆🤤💋",
    "I'LL SWING YOUR SISTER ON MY DICK SO HARD SHE'LL GET PREGNANT MID-SWING 💦💋",
    "PIG'S SON, I'LL LAY YOUR MOM ON THE ROAD AND FUCK HER 😂😆🤤",
    "HEY YOUR MOM'S PUSSY, MADARCHOD SON, WILL FIGHT YOUR DAD 😼😂🤤",
    "EVERY LANE ECHOES THAT YOUR MOM IS A RANDI WHORE 💋💋💦",
    "HEY I'LL FUCK YOUR SISTER, RANDI'S SON, DOG'S SON 😂👻🔥",
    "I FUCKED YOUR MOM SO HARD SHE PISSED ON THE BED 💦💦💦💦",
    "I SET YOUR SISTER'S PUSSY ON FIRE WITH MY THICK DICK 🔥🔥💦😆😆",
    "RANDI'S SON, I FUCKED YOUR MOM – NOW RUN",
    "HOW MUCH I FUCKED YOUR RANDI MOM'S PUSSY – NOW SEND YOUR SISTER 😆👻🤤",
    "I FUCKED YOUR SISTER SO HARD I TORE HER PUSSY – NOW SEND YOUR GF 😆💦🤤",
    "I FUCKED YOUR GF SO MUCH SHE BECAME MY RANDI – NOW I'LL FUCK YOUR MOM AGAIN ♥️💦😆😆😆😆",
    "IN EVERY BUSH A PEACOCK DANCES WATCHING YOUR MOM'S FUCK – EVERYONE SAYS ONCE MORE ONCE MORE 🤣🤣💦💋",
    "SEND YOUR DAD – YOU DON'T HAVE THE BALLS TO FIGHT DAD",
    "I'LL BOMB YOUR SISTER'S PUSSY AND BLOW IT UP, MOM'S DICK",
    "I'LL TAKE YOUR MOM ON A TRAIN, LAY HER ON THE TOP BUNK AND FUCK HER, PIG'S SON 🤣🤣💋💋",
    "I'LL UPLOAD YOUR MOM'S NUDES ON GOOGLE, SISTER'S DICK 👻🔥",
    "I'LL UPLOAD YOUR MOM'S NUDES ON GOOGLE, SISTER'S DICK 👻🔥",
    "I'LL FUCK YOUR SISTER, MAKE A VIDEO AND AUCTION IT ON XNXX.COM, DOG'S SON 💦💋",
    "I'LL UPLOAD YOUR MOM'S FUCKING ON PORNHUB, PIG'S SON 🤣💋💦",
    "HEY I'LL FUCK YOUR SISTER, RANDI'S SON – I'LL MAKE YOU LICK IT WITH A KNIFE, RANDI'S SON 🤣🤣",
    "I TORE YOUR MOM'S PUSSY, MOM'S DICK – GO GET IT STITCHED 👄👄",
    "YOUR SISTER'S PUSSY IS BLACK FROM MY DICK",
    "YOUR SISTER LOVES MY DICK – I FUCKED YOUR SISTER REAL CHEAP",
    "SON, YOU'LL FIGHT YOUR DAD – I'LL FUCK YOUR MOM NAKED 💦💋",
    "HAHAHA MY SON, NEXT TIME BRING YOUR MOM – DON'T CRY, LET ME FUCK HER WITH MY THICK DICK",
    "COME ON SON, I FORGAVE YOU 🤣 NOW SEND YOUR GF",
    "SHAME ON YOU – HOW MANY ABUSES YOUR SISTER'S PUSSY WILL HEAR ABOUT YOUR MOM AND SISTER",
    "HEY RANDI'S SON, YOU DON'T HAVE THE STATUS – BRING YOUR RANDI MOM, DON'T CRY HAHAHA",
    "KID MADARCHOD, I FUCKED YOUR MOM AND GAVE YOU A BROTHER",
    "PEACOCKS DANCE IN THE JUNGLE WATCHING YOUR MOM'S FUCK – EVERYONE SAYS ONCE MORE 🤣🤣💦💋",
    "SAND LIVES IN EVERY LANE – I FUCKED YOUR MOM AND MADE HER A RANDI 🤤🤣",
    "EVERYONE CALLS ME DADDY BECAUSE I GOT YOUR MOM PREGNANT 🤣🤣",
    "PIG'S SON, PIG DICK IN YOUR MOM'S PUSSY AND MY DICK IN YOUR SISTER'S",
    "COME ON SHOW YOUR MOM'S TITS",
    "HAHAHAHA KID, I FUCKED YOUR MOM NAKED",
    "YOUR GF IS SUPER SEXY – WE'LL MAKE HER DRINK AND FUCK HER WITH PEPSI",
    "2 RUPEE PEPSI – YOUR MOMMY IS THE SEXIEST 💋💦",
    "I'LL MAKE YOUR MOM FUCK WITH CREAMS, MADARCHOD'S SON 💦🤣",
    "I'LL CUM IN YOUR SISTER'S PUSSY AND RUN – HUI HUI HUI",
    "SPEED UP – YOUR SISTER FUCK, RANDI'S SON 💋💦🤣",
    "HEY MY SON WHY CAN'T YOU CATCH SPEED – YOUR DAD'S HAHAHA 🤣🤣",
    "LISTEN LISTEN PIG'S SON, PUBES MERCHANT – SEND YOUR MOMMY'S NUDES",
    "HEY LISTEN DICKHEAD – I'LL TEAR YOUR SISTER'S PUSSY",
    "I'LL FUCK YOUR MOM IN THE OPEN MARKET 🤣🤣💋",
    "MADARCHOD I'LL CHEW GUTKHA AND SPIT IN YOUR MOM'S PUSSY 🤣🤣",
    "I'LL STAB YOUR SISTER'S PUSSY WITH A KNIFE AND MAKE IT BLEED",
    "DON'T YOU HAVE A SISTER? WAIT 9 MONTHS – I'LL GIVE YOU A REAL ONE 🤣🤣🤩",
    "I'LL PARK PLANES IN YOUR MOM'S PUSSY AND FILL IT WITH FLIGHTS ✈️🛫",
    "I'LL BLOW A SUITCASE BOMB IN YOUR MOM'S PUSSY TILL HER PUBES BURN TO ASH 💣",
    "I'LL SHOVE A SCOOTER IN YOUR MOM'S PUSSY 👅",
    "I'LL STAB YOUR SISTER'S PUSSY WITH A KNIFE AND MAKE IT BLEED",
    "I'LL STAB YOUR SISTER'S PUSSY WITH A KNIFE AND MAKE IT BLEED",
    "I'LL CUT YOUR MOM'S PUSSY, FEED IT TO STREET DOGS 🦮 THEN THEY'LL EAT YOUR MOM'S PUSSY LIKE BREAD 🍞",
    "I'LL MILK IT ON YOUR SISTER UP AND DOWN 🆙🆒😙",
    "I'LL REACH HAND IN YOUR MOM'S PUSSY AND PULL OUT BABIES 😍",
    "BANANA PEELS IN YOUR SISTER'S PUSSY 🍌🍌😍",
    "I'LL INSTALL USERBOT IN YOUR SISTER'S PUSSY FOR CHEAP SPAM FUCKS",
    "YOUR SISTER IS A PRO WHORE 😋😛",
    "I'LL INSTALL AC IN YOUR MOM'S PUSSY – ALL THE HEAT WILL COME OUT",
    "I'LL FEED YOUR SISTER HORLICKS, MADARCHOD 😚",
    "I'LL SHOVE REBAR IN YOUR MOM'S ASS, MADARCHOD – HANG OFF IT AND KNOCK HER UP 😱😱",
    "YOUR MOM GETS BLESSED BY JITU BHAIYA FROM KOLKATA'S DICK 🤩🤩",
    "I'M YOUR MOMMY'S FANTASY, DICKHEAD – GO HANDLE YOUR SISTER 😈😈",
    "I WAS YOUR FIRST DAD, MADARCHOD",
    "I'LL JACK OFF TO XVIDEOS.COM IN YOUR SISTER'S PUSSY 🤡😹",
    "I'LL GANGBANG YOUR MOM WITH THE WHOLE GROUP 🙌🏻☠️",
    "I'LL RAM DICK IN YOUR ITEM'S ASS AND PULL OUT ANOTHER ONE LIKE YOU, MADARCHOD 🤘🏻🙌🏻☠️",
    "STAY IN YOUR LANE OR I'LL SHOVE A STICK UP YOUR ASS AND PULL IT FROM YOUR MOUTH – BODY WILL LOOK LIKE A STICK 🙄🤭🤭",
    "PLAYING LUDO WITH YOUR MOMMY, I'LL SHOVE MY DICK IN HER MOUTH ☝🏻☝🏻😬",
    "I'LL SWING YOUR SISTER ON MY DICK SO MUCH SHE'LL GIVE BIRTH MID-SWING 👀👯",
    "I'LL STICK BATTERY IN YOUR MOM'S PUSSY AND MAKE A POWERBANK 🔋 🔥🤩",
    ]
RAID = [
    "𝗠𝗔̂𝗔̂𝗗𝗔𝗥𝗖𝗛Ø𝗗 𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗠𝗘 𝗚𝗛𝗨𝗧𝗞𝗔 𝗞𝗛𝗔𝗔𝗞𝗘 𝗧𝗛𝗢𝗢𝗞 𝗗𝗨𝗡𝗚𝗔 🤣🤣",
    "𝗧𝗘𝗥𝗘 𝗕𝗘́𝗛𝗘𝗡 𝗞 𝗖𝗛𝗨𝗨́𝗧 𝗠𝗘 𝗖𝗛𝗔𝗞𝗨 𝗗𝗔𝗔𝗟 𝗞𝗔𝗥 𝗖𝗛𝗨𝗨́𝗧 𝗞𝗔 𝗞𝗛𝗢𝗢𝗡 𝗞𝗔𝗥 𝗗𝗨𝗚𝗔",
    "𝗧𝗘𝗥𝗜 𝗩𝗔𝗛𝗘𝗘𝗡 𝗡𝗛𝗜 𝗛𝗔𝗜 𝗞𝗬𝗔? 9 𝗠𝗔𝗛𝗜𝗡𝗘 𝗥𝗨𝗞 𝗦𝗔𝗚𝗜 𝗩𝗔𝗛𝗘𝗘𝗡 𝗗𝗘𝗧𝗔 𝗛𝗨 🤣🤣🤩",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞 𝗕𝗛𝗢𝗦𝗗𝗘 𝗠𝗘 𝗔𝗘𝗥𝗢𝗣𝗟𝗔𝗡𝗘𝗣𝗔𝗥𝗞 𝗞𝗔𝗥𝗞𝗘 𝗨𝗗𝗔𝗔𝗡 𝗕𝗛𝗔𝗥 𝗗𝗨𝗚𝗔 ✈️🛫",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗠𝗘 𝗦𝗨𝗧𝗟𝗜 𝗕𝗢𝗠𝗕 𝗙𝗢𝗗 𝗗𝗨𝗡𝗚𝗔 𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗜 𝗝𝗛𝗔𝗔𝗧𝗘 𝗝𝗔𝗟 𝗞𝗘 𝗞𝗛𝗔𝗔𝗞 𝗛𝗢 𝗝𝗔𝗬𝗘𝗚𝗜💣",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗠𝗘 𝗦𝗖𝗢𝗢𝗧𝗘𝗥 𝗗𝗔𝗔𝗟 𝗗𝗨𝗚𝗔👅",
    "𝗧𝗘𝗥𝗘 𝗕𝗘́𝗛𝗘𝗡 𝗞 𝗖𝗛𝗨𝗨́𝗧 𝗠𝗘 𝗖𝗛𝗔𝗞𝗨 𝗗𝗔𝗔𝗟 𝗞𝗔𝗥 𝗖𝗛𝗨𝗨́𝗧 𝗞𝗔 𝗞𝗛𝗢𝗢𝗡 𝗞𝗔𝗥 𝗗𝗨𝗚𝗔",
    "𝗧𝗘𝗥𝗘 𝗕𝗘́𝗛𝗘𝗡 𝗞 𝗖𝗛𝗨𝗨́𝗧 𝗠𝗘 𝗖𝗛𝗔𝗞𝗨 𝗗𝗔𝗔𝗟 𝗞𝗔𝗥 𝗖𝗛𝗨𝗨́𝗧 𝗞𝗔 𝗞𝗛𝗢𝗢𝗡 𝗞𝗔𝗥 𝗗𝗨𝗚𝗔",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗞𝗔𝗞𝗧𝗘 🤱 𝗚𝗔𝗟𝗜 𝗞𝗘 𝗞𝗨𝗧𝗧𝗢 🦮 𝗠𝗘 𝗕𝗔𝗔𝗧 𝗗𝗨𝗡𝗚𝗔 𝗣𝗛𝗜𝗥 🍞 𝗕𝗥𝗘𝗔𝗗 𝗞𝗜 𝗧𝗔𝗥𝗛 𝗞𝗛𝗔𝗬𝗘𝗡𝗚𝗘 𝗪𝗢 𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧",
    "𝗗𝗨𝗗𝗛 𝗛𝗜𝗟𝗔𝗔𝗨𝗡𝗚𝗔 𝗧𝗘𝗥𝗜 𝗩𝗔𝗛𝗘𝗘𝗡 𝗞𝗘 𝗨𝗣𝗥 𝗡𝗜𝗖𝗛𝗘 🆙🆒😙",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗠𝗘 ✋ 𝗛𝗔𝗧𝗧𝗛 𝗗𝗔𝗟𝗞𝗘 👶 𝗕𝗔𝗖𝗖𝗛𝗘 𝗡𝗜𝗞𝗔𝗟 𝗗𝗨𝗡𝗚𝗔 😍",
    "𝗧𝗘𝗥𝗜 𝗕𝗘𝗛𝗡 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗠𝗘 𝗞𝗘𝗟𝗘 𝗞𝗘 𝗖𝗛𝗜𝗟𝗞𝗘 🍌🍌😍",
    "𝗧𝗘𝗥𝗜 𝗕𝗛𝗘𝗡 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗠𝗘 𝗨𝗦𝗘𝗥𝗕𝗢𝗧 𝗟𝗔𝗚𝗔𝗔𝗨𝗡𝗚𝗔 𝗦𝗔𝗦𝗧𝗘 𝗦𝗣𝗔𝗠 𝗞𝗘 𝗖𝗛𝗢𝗗𝗘",
    "𝗧𝗘𝗥𝗜 𝗩𝗔𝗛𝗘𝗘𝗡 𝗗𝗛𝗔𝗡𝗗𝗛𝗘 𝗩𝗔𝗔𝗟𝗜 😋😛",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗘 𝗕𝗛𝗢𝗦𝗗𝗘 𝗠𝗘 𝗔𝗖 𝗟𝗔𝗚𝗔 𝗗𝗨𝗡𝗚𝗔 𝗦𝗔𝗔𝗥𝗜 𝗚𝗔𝗥𝗠𝗜 𝗡𝗜𝗞𝗔𝗟 𝗝𝗔𝗔𝗬𝗘𝗚𝗜",
    "𝗧𝗘𝗥𝗜 𝗩𝗔𝗛𝗘𝗘𝗡 𝗞𝗢 𝗛𝗢𝗥𝗟𝗜𝗖𝗞𝗦 𝗣𝗘𝗘𝗟𝗔𝗨𝗡𝗚𝗔 𝗠𝗔̂𝗔̂𝗗𝗔𝗥𝗖𝗛Ø𝗗😚",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗜 𝗚𝗔𝗔𝗡𝗗 𝗠𝗘 𝗦𝗔𝗥𝗜𝗬𝗔 𝗗𝗔𝗔𝗟 𝗗𝗨𝗡𝗚𝗔 𝗠𝗔̂𝗔̂𝗗𝗔𝗥𝗖𝗛Ø𝗗 𝗨𝗦𝗜 𝗦𝗔𝗥𝗜𝗬𝗘 𝗣𝗥 𝗧𝗔𝗡𝗚 𝗞𝗘 𝗕𝗔𝗖𝗛𝗘 𝗣𝗔𝗜𝗗𝗔 𝗛𝗢𝗡𝗚𝗘 😱😱",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗢 𝗞𝗢𝗟𝗞𝗔𝗧𝗔 𝗩𝗔𝗔𝗟𝗘 𝗝𝗜𝗧𝗨 𝗕𝗛𝗔𝗜𝗬𝗔 𝗞𝗔 𝗟𝗨𝗡𝗗 𝗠𝗨𝗕𝗔𝗥𝗔𝗞 🤩🤩",
    "𝗧𝗘𝗥𝗜 𝗠𝗨𝗠𝗠𝗬 𝗞𝗜 𝗙𝗔𝗡𝗧𝗔𝗦𝗬 𝗛𝗨 𝗟𝗔𝗪𝗗𝗘, 𝗧𝗨 𝗔𝗣𝗡𝗜 𝗕𝗛𝗘𝗡 𝗞𝗢 𝗦𝗠𝗕𝗛𝗔𝗔𝗟 😈😈",
    "𝗧𝗘𝗥𝗔 𝗣𝗘𝗛𝗟𝗔 𝗕𝗔𝗔𝗣 𝗛𝗨 𝗠𝗔̂𝗔̂𝗗𝗔𝗥𝗖𝗛Ø𝗗 ",
    "𝗧𝗘𝗥𝗜 𝗩𝗔𝗛𝗘𝗘𝗡 𝗞𝗘 𝗕𝗛𝗢𝗦𝗗𝗘 𝗠𝗘 𝗫𝗩𝗜𝗗𝗘𝗢𝗦.𝗖𝗢𝗠 𝗖𝗛𝗔𝗟𝗔 𝗞𝗘 𝗠𝗨𝗧𝗛 𝗠𝗔́𝗔̀𝗥𝗨𝗡𝗚𝗔 🤡😹",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗔 𝗚𝗥𝗢𝗨𝗣 𝗩𝗔𝗔𝗟𝗢𝗡 𝗦𝗔𝗔𝗧𝗛 𝗠𝗜𝗟𝗞𝗘 𝗚𝗔𝗡𝗚 𝗕𝗔𝗡𝗚 𝗞𝗥𝗨𝗡𝗚𝗔🙌🏻☠️ ",
    "𝗧𝗘𝗥𝗜 𝗜𝗧𝗘𝗠 𝗞𝗜 𝗚𝗔𝗔𝗡𝗗 𝗠𝗘 𝗟𝗨𝗡𝗗 𝗗𝗔𝗔𝗟𝗞𝗘,𝗧𝗘𝗥𝗘 𝗝𝗔𝗜𝗦𝗔 𝗘𝗞 𝗢𝗥 𝗡𝗜𝗞𝗔𝗔𝗟 𝗗𝗨𝗡𝗚𝗔 𝗠𝗔̂𝗔̂𝗗𝗔𝗥𝗖𝗛Ø𝗗🤘🏻🙌🏻☠️ ",
    "𝗔𝗨𝗞𝗔𝗔𝗧 𝗠𝗘 𝗥𝗘𝗛 𝗩𝗥𝗡𝗔 𝗚𝗔𝗔𝗡𝗗 𝗠𝗘 𝗗𝗔𝗡𝗗𝗔 𝗗𝗔𝗔𝗟 𝗞𝗘 𝗠𝗨𝗛 𝗦𝗘 𝗡𝗜𝗞𝗔𝗔𝗟 𝗗𝗨𝗡𝗚𝗔 𝗦𝗛𝗔𝗥𝗜𝗥 𝗕𝗛𝗜 𝗗𝗔𝗡𝗗𝗘 𝗝𝗘𝗦𝗔 𝗗𝗜𝗞𝗛𝗘𝗚𝗔 🙄🤭🤭",
    "𝗧𝗘𝗥𝗜 𝗠𝗨𝗠𝗠𝗬 𝗞𝗘 𝗦𝗔𝗔𝗧𝗛 𝗟𝗨𝗗𝗢 𝗞𝗛𝗘𝗟𝗧𝗘 𝗞𝗛𝗘𝗟𝗧𝗘 𝗨𝗦𝗞𝗘 𝗠𝗨𝗛 𝗠𝗘 𝗔𝗣𝗡𝗔 𝗟𝗢𝗗𝗔 𝗗𝗘 𝗗𝗨𝗡𝗚𝗔☝🏻☝🏻😬",
    "𝗧𝗘𝗥𝗜 𝗩𝗔𝗛𝗘𝗘𝗡 𝗞𝗢 𝗔𝗣𝗡𝗘 𝗟𝗨𝗡𝗗 𝗣𝗥 𝗜𝗧𝗡𝗔 𝗝𝗛𝗨𝗟𝗔𝗔𝗨𝗡𝗚𝗔 𝗞𝗜 𝗝𝗛𝗨𝗟𝗧𝗘 𝗝𝗛𝗨𝗟𝗧𝗘 𝗛𝗜 𝗕𝗔𝗖𝗛𝗔 𝗣𝗔𝗜𝗗𝗔 𝗞𝗥 𝗗𝗘𝗚𝗜👀👯 ",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗠𝗘𝗜 𝗕𝗔𝗧𝗧𝗘𝗥𝗬 𝗟𝗔𝗚𝗔 𝗞𝗘 𝗣𝗢𝗪𝗘𝗥𝗕𝗔𝗡𝗞 𝗕𝗔𝗡𝗔 𝗗𝗨𝗡𝗚𝗔 🔋 🔥🤩",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗠𝗘𝗜 𝗖++ 𝗦𝗧𝗥𝗜𝗡𝗚 𝗘𝗡𝗖𝗥𝗬𝗣𝗧𝗜𝗢𝗡 𝗟𝗔𝗚𝗔 𝗗𝗨𝗡𝗚𝗔 𝗕𝗔𝗛𝗧𝗜 𝗛𝗨𝗬𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗥𝗨𝗞 𝗝𝗔𝗬𝗘𝗚𝗜𝗜𝗜𝗜😈🔥😍",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗘 𝗚𝗔𝗔𝗡𝗗 𝗠𝗘𝗜 𝗝𝗛𝗔𝗔𝗗𝗨 𝗗𝗔𝗟 𝗞𝗘 𝗠𝗢𝗥 🦚 𝗕𝗔𝗡𝗔 𝗗𝗨𝗡𝗚𝗔𝗔 🤩🥵😱",
    "𝗧𝗘𝗥𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗠𝗘𝗜 𝗦𝗛𝗢𝗨𝗟𝗗𝗘𝗥𝗜𝗡𝗚 𝗞𝗔𝗥 𝗗𝗨𝗡𝗚𝗔𝗔 𝗛𝗜𝗟𝗔𝗧𝗘 𝗛𝗨𝗬𝗘 𝗕𝗛𝗜 𝗗𝗔𝗥𝗗 𝗛𝗢𝗚𝗔𝗔𝗔😱🤮👺",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗢 𝗥𝗘𝗗𝗜 𝗣𝗘 𝗕𝗔𝗜𝗧𝗛𝗔𝗟 𝗞𝗘 𝗨𝗦𝗦𝗘 𝗨𝗦𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗕𝗜𝗟𝗪𝗔𝗨𝗡𝗚𝗔𝗔 💰 😵🤩",
    "𝗕𝗛𝗢𝗦𝗗𝗜𝗞𝗘 𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗠𝗘𝗜 4 𝗛𝗢𝗟𝗘 𝗛𝗔𝗜 𝗨𝗡𝗠𝗘 𝗠𝗦𝗘𝗔𝗟 𝗟𝗔𝗚𝗔 𝗕𝗔𝗛𝗨𝗧 𝗕𝗔𝗛𝗘𝗧𝗜 𝗛𝗔𝗜 𝗕𝗛𝗢𝗙𝗗𝗜𝗞𝗘👊🤮🤢🤢",
    "𝗧𝗘𝗥𝗜 𝗕𝗔𝗛𝗘𝗡 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗠𝗘𝗜 𝗕𝗔𝗥𝗚𝗔𝗗 𝗞𝗔 𝗣𝗘𝗗 𝗨𝗚𝗔 𝗗𝗨𝗡𝗚𝗔𝗔 𝗖𝗢𝗥𝗢𝗡𝗔 𝗠𝗘𝗜 𝗦𝗔𝗕 𝗢𝗫𝗬𝗚𝗘𝗡 𝗟𝗘𝗞𝗔𝗥 𝗝𝗔𝗬𝗘𝗡𝗚𝗘🤢🤩🥳",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗠𝗘𝗜 𝗦𝗨𝗗𝗢 𝗟𝗔𝗚𝗔 𝗞𝗘 𝗕𝗜𝗚𝗦𝗣𝗔𝗠 𝗟𝗔𝗚𝗔 𝗞𝗘 9999 𝗙𝗨𝗖𝗞 𝗟𝗔𝗚𝗔𝗔 𝗗𝗨 🤩🥳🔥",
    "𝗧𝗘𝗥𝗜 𝗩𝗔𝗛𝗘𝗡 𝗞𝗘 𝗕𝗛𝗢𝗦𝗗𝗜𝗞𝗘 𝗠𝗘𝗜 𝗕𝗘𝗦𝗔𝗡 𝗞𝗘 𝗟𝗔𝗗𝗗𝗨 𝗕𝗛𝗔𝗥 𝗗𝗨𝗡𝗚𝗔🤩🥳🔥😈",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗞𝗛𝗢𝗗 𝗞𝗘 𝗨𝗦𝗠𝗘 𝗖𝗬𝗟𝗜𝗡𝗗𝗘𝗥 ⛽️ 𝗙𝗜𝗧 𝗞𝗔𝗥𝗞𝗘 𝗨𝗦𝗠𝗘𝗘 𝗗𝗔𝗟 𝗠𝗔𝗞𝗛𝗔𝗡𝗜 𝗕𝗔𝗡𝗔𝗨𝗡𝗚𝗔𝗔𝗔🤩👊🔥",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗠𝗘𝗜 𝗦𝗛𝗘𝗘𝗦𝗛𝗔 𝗗𝗔𝗟 𝗗𝗨𝗡𝗚𝗔𝗔𝗔 𝗔𝗨𝗥 𝗖𝗛𝗔𝗨𝗥𝗔𝗛𝗘 𝗣𝗘 𝗧𝗔𝗔𝗡𝗚 𝗗𝗨𝗡𝗚𝗔 𝗕𝗛𝗢𝗦𝗗𝗜𝗞𝗘😈😱🤩",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗠𝗘𝗜 𝗖𝗥𝗘𝗗𝗜𝗧 𝗖𝗔𝗥𝗗 𝗗𝗔𝗟 𝗞𝗘 𝗔𝗚𝗘 𝗦𝗘 500 𝗞𝗘 𝗞𝗔𝗔𝗥𝗘 𝗞𝗔𝗔𝗥𝗘 𝗡𝗢𝗧𝗘 𝗡𝗜𝗞𝗔𝗟𝗨𝗡𝗚𝗔𝗔 𝗕𝗛𝗢𝗦𝗗𝗜𝗞𝗘💰💰🤩",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗘 𝗦𝗔𝗧𝗛 𝗦𝗨𝗔𝗥 𝗞𝗔 𝗦𝗘𝗫 𝗞𝗔𝗥𝗪𝗔 𝗗𝗨𝗡𝗚𝗔𝗔 𝗘𝗞 𝗦𝗔𝗧𝗛 6-6 𝗕𝗔𝗖𝗛𝗘 𝗗𝗘𝗚𝗜💰🔥😱",
    "𝗧𝗘𝗥𝗜 𝗕𝗔𝗛𝗘𝗡 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗠𝗘𝗜 𝗔𝗣𝗣𝗟𝗘 𝗞𝗔 18𝗪 𝗪𝗔𝗟𝗔 𝗖𝗛𝗔𝗥𝗚𝗘𝗥 🔥🤩",
    "𝗧𝗘𝗥𝗜 𝗕𝗔𝗛𝗘𝗡 𝗞𝗜 𝗚𝗔𝗔𝗡𝗗 𝗠𝗘𝗜 𝗢𝗡𝗘𝗣𝗟𝗨𝗦 𝗞𝗔 𝗪𝗥𝗔𝗣 𝗖𝗛𝗔𝗥𝗚𝗘𝗥 30𝗪 𝗛𝗜𝗚𝗛 𝗣𝗢𝗪𝗘𝗥 💥😂😎",
    "𝗧𝗘𝗥𝗜 𝗕𝗔𝗛𝗘𝗡 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗞𝗢 𝗔𝗠𝗔𝗭𝗢𝗡 𝗦𝗘 𝗢𝗥𝗗𝗘𝗥 𝗞𝗔𝗥𝗨𝗡𝗚𝗔 10 𝗿𝘀 𝗠𝗘𝗜 𝗔𝗨𝗥 𝗙𝗟𝗜𝗣𝗞𝗔𝗥𝗧 𝗣𝗘 20 𝗥𝗦 𝗠𝗘𝗜 𝗕𝗘𝗖𝗛 𝗗𝗨𝗡𝗚𝗔🤮👿😈🤖",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗜 𝗕𝗔𝗗𝗜 𝗕𝗛𝗨𝗡𝗗 𝗠𝗘 𝗭𝗢𝗠𝗔𝗧𝗢 𝗗𝗔𝗟 𝗞𝗘 𝗦𝗨𝗕𝗪𝗔𝗬 𝗞𝗔 𝗕𝗙𝗙 𝗩𝗘𝗚 𝗦𝗨𝗕 𝗖𝗢𝗠𝗕𝗢 [15𝗰𝗺 , 16 𝗶𝗻𝗰𝗵𝗲𝘀 ] 𝗢𝗥𝗗𝗘𝗥 𝗖𝗢𝗗 𝗞𝗥𝗩𝗔𝗨𝗡𝗚𝗔 𝗢𝗥 𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗝𝗔𝗕 𝗗𝗜𝗟𝗜𝗩𝗘𝗥𝗬 𝗗𝗘𝗡𝗘 𝗔𝗬𝗘𝗚𝗜 𝗧𝗔𝗕 𝗨𝗦𝗣𝗘 𝗝𝗔𝗔𝗗𝗨 𝗞𝗥𝗨𝗡𝗚𝗔 𝗢𝗥 𝗙𝗜𝗥 9 𝗠𝗢𝗡𝗧𝗛 𝗕𝗔𝗔𝗗 𝗩𝗢 𝗘𝗞 𝗢𝗥 𝗙𝗥𝗘𝗘 𝗗𝗜𝗟𝗜𝗩𝗘𝗥𝗬 𝗗𝗘𝗚𝗜🙀👍🥳🔥",
    "𝗧𝗘𝗥𝗜 𝗕𝗛𝗘𝗡 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗞𝗔𝗔𝗟𝗜🙁🤣💥",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗠𝗘 𝗖𝗛𝗔𝗡𝗚𝗘𝗦 𝗖𝗢𝗠𝗠𝗜𝗧 𝗞𝗥𝗨𝗚𝗔 𝗙𝗜𝗥 𝗧𝗘𝗥𝗜 𝗕𝗛𝗘𝗘𝗡 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗔𝗨𝗧𝗢𝗠𝗔𝗧𝗜𝗖𝗔𝗟𝗟𝗬 𝗨𝗣𝗗𝗔𝗧𝗘 𝗛𝗢𝗝𝗔𝗔𝗬𝗘𝗚𝗜🤖🙏🤔",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗨𝗦𝗜 𝗞𝗘 𝗕𝗛𝗢𝗦𝗗𝗘 𝗠𝗘𝗜 𝗜𝗡𝗗𝗜𝗔𝗡 𝗥𝗔𝗜𝗟𝗪𝗔𝗬 🚂💥😂",
    "𝗧𝗨 𝗧𝗘𝗥𝗜 𝗕𝗔𝗛𝗘𝗡 𝗧𝗘𝗥𝗔 𝗞𝗛𝗔𝗡𝗗𝗔𝗡 𝗦𝗔𝗕 𝗕𝗔𝗛𝗘𝗡 𝗞𝗘 𝗟𝗔𝗪𝗗𝗘 𝗥Æ𝗡𝗗𝗜 𝗛𝗔𝗜 𝗥Æ𝗡𝗗𝗜 🤢✅🔥",
    "𝗧𝗘𝗥𝗜 𝗕𝗔𝗛𝗘𝗡 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗠𝗘𝗜 𝗜𝗢𝗡𝗜𝗖 𝗕𝗢𝗡𝗗 𝗕𝗔𝗡𝗔 𝗞𝗘 𝗩𝗜𝗥𝗚𝗜𝗡𝗜𝗧𝗬 𝗟𝗢𝗢𝗦𝗘 𝗞𝗔𝗥𝗪𝗔 𝗗𝗨𝗡𝗚𝗔 𝗨𝗦𝗞𝗜 📚 😎🤩",
    "𝗧𝗘𝗥𝗜 𝗥Æ𝗡𝗗𝗜 𝗠𝗔́𝗔̀ 𝗦𝗘 𝗣𝗨𝗖𝗛𝗡𝗔 𝗕𝗔𝗔𝗣 𝗞𝗔 𝗡𝗔𝗔𝗠 𝗕𝗔𝗛𝗘𝗡 𝗞𝗘 𝗟𝗢𝗗𝗘𝗘𝗘𝗘𝗘 🤩🥳😳",
    "𝗧𝗨 𝗔𝗨𝗥 𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗗𝗢𝗡𝗢 𝗞𝗜 𝗕𝗛𝗢𝗦𝗗𝗘 𝗠𝗘𝗜 𝗠𝗘𝗧𝗥𝗢 𝗖𝗛𝗔𝗟𝗪𝗔 𝗗𝗨𝗡𝗚𝗔 𝗠𝗔𝗗𝗔𝗥𝗫𝗛𝗢𝗗 🚇🤩😱🥶",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗢 𝗜𝗧𝗡𝗔 𝗖𝗛𝗢𝗗𝗨𝗡𝗚𝗔 𝗧𝗘𝗥𝗔 𝗕𝗔𝗔𝗣 𝗕𝗛𝗜 𝗨𝗦𝗞𝗢 𝗣𝗔𝗛𝗖𝗛𝗔𝗡𝗔𝗡𝗘 𝗦𝗘 𝗠𝗔𝗡𝗔 𝗞𝗔𝗥 𝗗𝗘𝗚𝗔😂👿🤩",
    "𝗧𝗘𝗥𝗜 𝗕𝗔𝗛𝗘𝗡 𝗞𝗘 𝗕𝗛𝗢𝗦𝗗𝗘 𝗠𝗘𝗜 𝗛𝗔𝗜𝗥 𝗗𝗥𝗬𝗘𝗥 𝗖𝗛𝗔𝗟𝗔 𝗗𝗨𝗡𝗚𝗔𝗔💥🔥🔥",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗠𝗘𝗜 𝗧𝗘𝗟𝗘𝗚𝗥𝗔𝗠 𝗞𝗜 𝗦𝗔𝗥𝗜 𝗥Æ𝗡𝗗𝗜𝗬𝗢𝗡 𝗞𝗔 𝗥Æ𝗡𝗗𝗜 𝗞𝗛𝗔𝗡𝗔 𝗞𝗛𝗢𝗟 𝗗𝗨𝗡𝗚𝗔𝗔👿🤮😎",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗔𝗟𝗘𝗫𝗔 𝗗𝗔𝗟 𝗞𝗘𝗘 𝗗𝗝 𝗕𝗔𝗝𝗔𝗨𝗡𝗚𝗔𝗔𝗔 🎶 ⬆️🤩💥",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗘 𝗕𝗛𝗢𝗦𝗗𝗘 𝗠𝗘𝗜 𝗚𝗜𝗧𝗛𝗨𝗕 𝗗𝗔𝗟 𝗞𝗘 𝗔𝗣𝗡𝗔 𝗕𝗢𝗧 𝗛𝗢𝗦𝗧 𝗞𝗔𝗥𝗨𝗡𝗚𝗔𝗔 🤩👊👤😍",
    "𝗧𝗘𝗥𝗜 𝗕𝗔𝗛𝗘𝗡 𝗞𝗔 𝗩𝗣𝗦 𝗕𝗔𝗡𝗔 𝗞𝗘 24*7 𝗕𝗔𝗦𝗛 𝗖𝗛𝗨𝗗𝗔𝗜 𝗖𝗢𝗠𝗠𝗔𝗡𝗗 𝗗𝗘 𝗗𝗨𝗡𝗚𝗔𝗔 🤩💥🔥🔥",
    "𝗧𝗘𝗥𝗜 𝗠𝗨𝗠𝗠𝗬 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗠𝗘𝗜 𝗧𝗘𝗥𝗘 𝗟𝗔𝗡𝗗 𝗞𝗢 𝗗𝗔𝗟 𝗞𝗘 𝗞𝗔𝗔𝗧 𝗗𝗨𝗡𝗚𝗔 𝗠𝗔̂𝗔̂𝗗𝗔𝗥𝗖𝗛Ø𝗗 🔪😂🔥",
    "𝗦𝗨𝗡 𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗔 𝗕𝗛𝗢𝗦𝗗𝗔 𝗔𝗨𝗥 𝗧𝗘𝗥𝗜 𝗕𝗔𝗛𝗘𝗡 𝗞𝗔 𝗕𝗛𝗜 𝗕𝗛𝗢𝗦𝗗𝗔 👿😎👊",
    "𝗧𝗨𝗝𝗛𝗘 𝗗𝗘𝗞𝗛 𝗞𝗘 𝗧𝗘𝗥𝗜 𝗥Æ𝗡𝗗𝗜 𝗕𝗔𝗛𝗘𝗡 𝗣𝗘 𝗧𝗔𝗥𝗔𝗦 𝗔𝗧𝗔 𝗛𝗔𝗜 𝗠𝗨𝗝𝗛𝗘 𝗕𝗔𝗛𝗘𝗡 𝗞𝗘 𝗟𝗢𝗗𝗘𝗘𝗘𝗘 👿💥🤩🔥",
    "𝗦𝗨𝗡 𝗠𝗔̂𝗔̂𝗗𝗔𝗥𝗖𝗛Ø𝗗 𝗝𝗬𝗔𝗗𝗔 𝗡𝗔 𝗨𝗖𝗛𝗔𝗟 𝗠𝗔́𝗔̀ 𝗖𝗛𝗢𝗗 𝗗𝗘𝗡𝗚𝗘 𝗘𝗞 𝗠𝗜𝗡 𝗠𝗘𝗜 ✅🤣🔥🤩",
    "𝗔𝗣𝗡𝗜 𝗔𝗠𝗠𝗔 𝗦𝗘 𝗣𝗨𝗖𝗛𝗡𝗔 𝗨𝗦𝗞𝗢 𝗨𝗦 𝗞𝗔𝗔𝗟𝗜 𝗥𝗔𝗔𝗧 𝗠𝗘𝗜 𝗞𝗔𝗨𝗡 𝗖𝗛𝗢𝗗𝗡𝗘𝗘 𝗔𝗬𝗔 𝗧𝗛𝗔𝗔𝗔! 𝗧𝗘𝗥𝗘 𝗜𝗦 𝗣𝗔𝗣𝗔 𝗞𝗔 𝗡𝗔𝗔𝗠 𝗟𝗘𝗚𝗜 😂👿😳",
    "𝗧𝗢𝗛𝗔𝗥 𝗕𝗔𝗛𝗜𝗡 𝗖𝗛𝗢𝗗𝗨 𝗕𝗕𝗔𝗛𝗘𝗡 𝗞𝗘 𝗟𝗔𝗪𝗗𝗘 𝗨𝗦𝗠𝗘 𝗠𝗜𝗧𝗧𝗜 𝗗𝗔𝗟 𝗞𝗘 𝗖𝗘𝗠𝗘𝗡𝗧 𝗦𝗘 𝗕𝗛𝗔𝗥 𝗗𝗨 🏠🤢🤩💥",
    "𝗧𝗨𝗝𝗛𝗘 𝗔𝗕 𝗧𝗔𝗞 𝗡𝗔𝗛𝗜 𝗦𝗠𝗝𝗛 𝗔𝗬𝗔 𝗞𝗜 𝗠𝗔𝗜 𝗛𝗜 𝗛𝗨 𝗧𝗨𝗝𝗛𝗘 𝗣𝗔𝗜𝗗𝗔 𝗞𝗔𝗥𝗡𝗘 𝗪𝗔𝗟𝗔 𝗕𝗛𝗢𝗦𝗗𝗜𝗞𝗘𝗘 𝗔𝗣𝗡𝗜 𝗠𝗔́𝗔̀ 𝗦𝗘 𝗣𝗨𝗖𝗛 𝗥Æ𝗡𝗗𝗜 𝗞𝗘 𝗕𝗔𝗖𝗛𝗘𝗘𝗘𝗘 🤩👊👤😍",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗘 𝗕𝗛𝗢𝗦𝗗𝗘 𝗠𝗘𝗜 𝗦𝗣𝗢𝗧𝗜𝗙𝗬 𝗗𝗔𝗟 𝗞𝗘 𝗟𝗢𝗙𝗜 𝗕𝗔𝗝𝗔𝗨𝗡𝗚𝗔 𝗗𝗜𝗡 𝗕𝗛𝗔𝗥 😍🎶🎶💥",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗔 𝗡𝗔𝗬𝗔 𝗥Æ𝗡𝗗𝗜 𝗞𝗛𝗔𝗡𝗔 𝗞𝗛𝗢𝗟𝗨𝗡𝗚𝗔 𝗖𝗛𝗜𝗡𝗧𝗔 𝗠𝗔𝗧 𝗞𝗔𝗥 👊🤣🤣😳",
    "𝗧𝗘𝗥𝗔 𝗕𝗔𝗔𝗣 𝗛𝗨 𝗕𝗛𝗢𝗦𝗗𝗜𝗞𝗘 𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗢 𝗥Æ𝗡𝗗𝗜 𝗞𝗛𝗔𝗡𝗘 𝗣𝗘 𝗖𝗛𝗨𝗗𝗪𝗔 𝗞𝗘 𝗨𝗦 𝗣𝗔𝗜𝗦𝗘 𝗞𝗜 𝗗𝗔𝗔𝗥𝗨 𝗣𝗘𝗘𝗧𝗔 𝗛𝗨 🍷🤩🔥",
    "𝗧𝗘𝗥𝗜 𝗕𝗔𝗛𝗘𝗡 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗠𝗘𝗜 𝗔𝗣𝗡𝗔 𝗕𝗔𝗗𝗔 𝗦𝗔 𝗟𝗢𝗗𝗔 𝗚𝗛𝗨𝗦𝗦𝗔 𝗗𝗨𝗡𝗚𝗔𝗔 𝗞𝗔𝗟𝗟𝗔𝗔𝗣 𝗞𝗘 𝗠𝗔𝗥 𝗝𝗔𝗬𝗘𝗚𝗜 🤩😳😳🔥",
    "𝗧𝗢𝗛𝗔𝗥 𝗠𝗨𝗠𝗠𝗬 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗠𝗘𝗜 𝗣𝗨𝗥𝗜 𝗞𝗜 𝗣𝗨𝗥𝗜 𝗞𝗜𝗡𝗚𝗙𝗜𝗦𝗛𝗘𝗥 𝗞𝗜 𝗕𝗢𝗧𝗧𝗟𝗘 𝗗𝗔𝗟 𝗞𝗘 𝗧𝗢𝗗 𝗗𝗨𝗡𝗚𝗔 𝗔𝗡𝗗𝗘𝗥 𝗛𝗜 😱😂🤩",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗢 𝗜𝗧𝗡𝗔 𝗖𝗛𝗢𝗗𝗨𝗡𝗚𝗔 𝗞𝗜 𝗦𝗔𝗣𝗡𝗘 𝗠𝗘𝗜 𝗕𝗛𝗜 𝗠𝗘𝗥𝗜 𝗖𝗛𝗨𝗗𝗔𝗜 𝗬𝗔𝗔𝗗 𝗞𝗔𝗥𝗘𝗚𝗜 𝗥Æ𝗡𝗗𝗜 🥳😍👊💥",
    "𝗧𝗘𝗥𝗜 𝗠𝗨𝗠𝗠𝗬 𝗔𝗨𝗥 𝗕𝗔𝗛𝗘𝗡 𝗞𝗢 𝗗𝗔𝗨𝗗𝗔 𝗗𝗔𝗨𝗗𝗔 𝗡𝗘 𝗖𝗛𝗢𝗗𝗨𝗡𝗚𝗔 𝗨𝗡𝗞𝗘 𝗡𝗢 𝗕𝗢𝗟𝗡𝗘 𝗣𝗘 𝗕𝗛𝗜 𝗟𝗔𝗡𝗗 𝗚𝗛𝗨𝗦𝗔 𝗗𝗨𝗡𝗚𝗔 𝗔𝗡𝗗𝗘𝗥 𝗧𝗔𝗞 😎😎🤣🔥",
    "𝗧𝗘𝗥𝗜 𝗠𝗨𝗠𝗠𝗬 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗞𝗢 𝗢𝗡𝗟𝗜𝗡𝗘 𝗢𝗟𝗫 𝗣𝗘 𝗕𝗘𝗖𝗛𝗨𝗡𝗚𝗔 𝗔𝗨𝗥 𝗣𝗔𝗜𝗦𝗘 𝗦𝗘 𝗧𝗘𝗥𝗜 𝗕𝗔𝗛𝗘𝗡 𝗞𝗔 𝗞𝗢𝗧𝗛𝗔 𝗞𝗛𝗢𝗟 𝗗𝗨𝗡𝗚𝗔 😎🤩😝😍",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗘 𝗕𝗛𝗢𝗦𝗗𝗔 𝗜𝗧𝗡𝗔 𝗖𝗛𝗢𝗗𝗨𝗡𝗚𝗔 𝗞𝗜 𝗧𝗨 𝗖𝗔𝗛 𝗞𝗘 𝗕𝗛𝗜 𝗪𝗢 𝗠𝗔𝗦𝗧 𝗖𝗛𝗨𝗗𝗔𝗜 𝗦𝗘 𝗗𝗨𝗥 𝗡𝗛𝗜 𝗝𝗔 𝗣𝗔𝗬𝗘𝗚𝗔𝗔 😏😏🤩😍",
    "𝗦𝗨𝗡 𝗕𝗘 𝗥Æ𝗡𝗗𝗜 𝗞𝗜 𝗔𝗨𝗟𝗔𝗔𝗗 𝗧𝗨 𝗔𝗣𝗡𝗜 𝗕𝗔𝗛𝗘𝗡 𝗦𝗘 𝗦𝗘𝗘𝗞𝗛 𝗞𝗨𝗖𝗛 𝗞𝗔𝗜𝗦𝗘 𝗚𝗔𝗔𝗡𝗗 𝗠𝗔𝗥𝗪𝗔𝗧𝗘 𝗛𝗔𝗜😏🤬🔥💥",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗔 𝗬𝗔𝗔𝗥 𝗛𝗨 𝗠𝗘𝗜 𝗔𝗨𝗥 𝗧𝗘𝗥𝗜 𝗕𝗔𝗛𝗘𝗡 𝗞𝗔 𝗣𝗬𝗔𝗔𝗥 𝗛𝗨 𝗠𝗘𝗜 𝗔𝗝𝗔 𝗠𝗘𝗥𝗔 𝗟𝗔𝗡𝗗 𝗖𝗛𝗢𝗢𝗦 𝗟𝗘 🤩🤣💥",
    "𝗧𝗘𝗥𝗜 𝗕𝗛𝗘𝗡 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗠𝗘 𝗨𝗦𝗘𝗥𝗕𝗢𝗧 𝗟𝗔𝗚𝗔𝗔𝗨𝗡𝗚𝗔 𝗦𝗔𝗦𝗧𝗘 𝗦𝗣𝗔𝗠 𝗞𝗘 𝗖𝗛𝗢𝗗𝗘",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗜 𝗚𝗔𝗔𝗡𝗗 𝗠𝗘 𝗦𝗔𝗥𝗜𝗬𝗔 𝗗𝗔𝗔𝗟 𝗗𝗨𝗡𝗚𝗔 𝗠𝗔̂𝗔̂𝗗𝗔𝗥𝗖𝗛Ø𝗗 𝗨𝗦𝗜 𝗦𝗔𝗥𝗜𝗬𝗘 𝗣𝗥 𝗧𝗔𝗡𝗚 𝗞𝗘 𝗕𝗔𝗖𝗛𝗘 𝗣𝗔𝗜𝗗𝗔 𝗛𝗢𝗡𝗚𝗘 😱😱",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗠𝗘 ✋ 𝗛𝗔𝗧𝗧𝗛 𝗗𝗔𝗟𝗞𝗘 👶 𝗕𝗔𝗖𝗖𝗛𝗘 𝗡𝗜𝗞𝗔𝗟 𝗗𝗨𝗡𝗚𝗔 😍",
    "𝗧𝗘𝗥𝗜 𝗕𝗘𝗛𝗡 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗠𝗘 𝗞𝗘𝗟𝗘 𝗞𝗘 𝗖𝗛𝗜𝗟𝗞𝗘 🤤🤤",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗠𝗘 𝗦𝗨𝗧𝗟𝗜 𝗕𝗢𝗠𝗕 𝗙𝗢𝗗 𝗗𝗨𝗡𝗚𝗔 𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗜 𝗝𝗛𝗔𝗔𝗧𝗘 𝗝𝗔𝗟 𝗞𝗘 𝗞𝗛𝗔𝗔𝗞 𝗛𝗢 𝗝𝗔𝗬𝗘𝗚𝗜💣💋",
    "𝗧𝗘𝗥𝗜 𝗩𝗔𝗛𝗘𝗘𝗡 𝗞𝗢 𝗛𝗢𝗥𝗟𝗜𝗖𝗞𝗦 𝗣𝗘𝗘𝗟𝗔𝗞𝗘 𝗖𝗛𝗢𝗗𝗨𝗡𝗚𝗔 𝗠𝗔̂𝗔̂𝗗𝗔𝗥𝗖𝗛Ø𝗗😚",
    "𝗧𝗘𝗥𝗜 𝗜𝗧𝗘𝗠 𝗞𝗜 𝗚𝗔𝗔𝗡𝗗 𝗠𝗘 𝗟𝗨𝗡𝗗 𝗗𝗔𝗔𝗟𝗞𝗘,𝗧𝗘𝗥𝗘 𝗝𝗔𝗜𝗦𝗔 𝗘𝗞 𝗢𝗥 𝗡𝗜𝗞𝗔𝗔𝗟 𝗗𝗨𝗡𝗚𝗔 𝗠𝗔̂𝗔̂𝗗𝗔𝗥𝗖𝗛Ø𝗗😆🤤💋",
    "𝗧𝗘𝗥𝗜 𝗩𝗔𝗛𝗘𝗘𝗡 𝗞𝗢 𝗔𝗣𝗡𝗘 𝗟𝗨𝗡𝗗 𝗣𝗥 𝗜𝗧𝗡𝗔 𝗝𝗛𝗨𝗟𝗔𝗔𝗨𝗡𝗚𝗔 𝗞𝗜 𝗝𝗛𝗨𝗟𝗧𝗘 𝗝𝗛𝗨𝗟𝗧𝗘 𝗛𝗜 𝗕𝗔𝗖𝗛𝗔 𝗣𝗔𝗜𝗗𝗔 𝗞𝗥 𝗗𝗘𝗚𝗜 💦💋",
    "𝗦𝗨𝗔𝗥 𝗞𝗘 𝗣𝗜𝗟𝗟𝗘 𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀𝗞𝗢 𝗦𝗔𝗗𝗔𝗞 𝗣𝗥 𝗟𝗜𝗧𝗔𝗞𝗘 𝗖𝗛𝗢𝗗 𝗗𝗨𝗡𝗚𝗔 😂😆🤤",
    "𝗔𝗕𝗘 𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀𝗞𝗔 𝗕𝗛𝗢𝗦𝗗𝗔 𝗠𝗔𝗗𝗘𝗥𝗖𝗛𝗢𝗢𝗗 𝗞𝗥 𝗣𝗜𝗟𝗟𝗘 𝗣𝗔𝗣𝗔 𝗦𝗘 𝗟𝗔𝗗𝗘𝗚𝗔 𝗧𝗨 😼😂🤤",
    "𝗚𝗔𝗟𝗜 𝗚𝗔𝗟𝗜 𝗡𝗘 𝗦𝗛𝗢𝗥 𝗛𝗘 𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗥Æ𝗡𝗗𝗜 𝗖𝗛𝗢𝗥 𝗛𝗘 💋💋💦",
    "𝗔𝗕𝗘 𝗧𝗘𝗥𝗜 𝗕𝗘́𝗛𝗘𝗡 𝗞𝗢 𝗖𝗛𝗢𝗗𝗨 𝗥Æ𝗡𝗗𝗜𝗞𝗘 𝗣𝗜𝗟𝗟𝗘 𝗞𝗨𝗧𝗧𝗘 𝗞𝗘 𝗖𝗛𝗢𝗗𝗘 😂👻🔥",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀𝗞𝗢 𝗔𝗜𝗦𝗘 𝗖𝗛𝗢𝗗𝗔 𝗔𝗜𝗦𝗘 𝗖𝗛𝗢𝗗𝗔 𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀𝗔 𝗕𝗘𝗗 𝗣𝗘𝗛𝗜 𝗠𝗨𝗧𝗛 𝗗𝗜𝗔 💦💦💦💦",
    "𝗧𝗘𝗥𝗜 𝗕𝗘́𝗛𝗘𝗡 𝗞𝗘 𝗕𝗛𝗢𝗦𝗗𝗘 𝗠𝗘 𝗔𝗔𝗔𝗚 𝗟𝗔𝗚𝗔𝗗𝗜𝗔 𝗠𝗘𝗥𝗔 𝗠𝗢𝗧𝗔 𝗟𝗨𝗡𝗗 𝗗𝗔𝗟𝗞𝗘 🔥🔥💦😆😆",
    "𝗥Æ𝗡𝗗𝗜𝗞𝗘 𝗕𝗔𝗖𝗛𝗛𝗘 𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀𝗞𝗢 𝗖𝗛𝗢𝗗𝗨 𝗖𝗛𝗔𝗟 𝗡𝗜𝗞𝗔𝗟",
    "𝗞𝗜𝗧𝗡𝗔 𝗖𝗛𝗢𝗗𝗨 𝗧𝗘𝗥𝗜 𝗥Æ𝗡𝗗𝗜 𝗠𝗔́𝗔̀𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧𝗛 𝗔𝗕𝗕 𝗔𝗣𝗡𝗜 𝗕𝗘́𝗛𝗘𝗡 𝗞𝗢 𝗕𝗛𝗘𝗝 😆👻🤤",
    "𝗧𝗘𝗥𝗜 𝗕𝗘́𝗛𝗘𝗡 𝗞𝗢𝗧𝗢 𝗖𝗛𝗢𝗗 𝗖𝗛𝗢𝗗𝗞𝗘 𝗣𝗨𝗥𝗔 𝗙𝗔𝗔𝗗 𝗗𝗜𝗔 𝗖𝗛𝗨𝗨́𝗧𝗛 𝗔𝗕𝗕 𝗧𝗘𝗥𝗜 𝗚𝗙 𝗞𝗢 𝗕𝗛𝗘𝗝 😆💦🤤",
    "𝗧𝗘𝗥𝗜 𝗚𝗙 𝗞𝗢 𝗘𝗧𝗡𝗔 𝗖𝗛𝗢𝗗𝗔 𝗕𝗘́𝗛𝗘𝗡 𝗞𝗘 𝗟𝗢𝗗𝗘 𝗧𝗘𝗥𝗜 𝗚𝗙 𝗧𝗢 𝗠𝗘𝗥𝗜 𝗥Æ𝗡𝗗𝗜 𝗕𝗔𝗡𝗚𝗔𝗬𝗜 𝗔𝗕𝗕 𝗖𝗛𝗔𝗟 𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀𝗞𝗢 𝗖𝗛𝗢𝗗𝗧𝗔 𝗙𝗜𝗥𝗦𝗘 ♥️💦😆😆😆😆",
    "𝗛𝗔𝗥𝗜 𝗛𝗔𝗥𝗜 𝗚𝗛𝗔𝗔𝗦 𝗠𝗘 𝗝𝗛𝗢𝗣𝗗𝗔 𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀𝗞𝗔 𝗕𝗛𝗢𝗦𝗗𝗔 🤣🤣💋💦",
    "𝗖𝗛𝗔𝗟 𝗧𝗘𝗥𝗘 𝗕𝗔𝗔𝗣 𝗞𝗢 𝗕𝗛𝗘𝗝 𝗧𝗘𝗥𝗔 𝗕𝗔𝗦𝗞𝗔 𝗡𝗛𝗜 𝗛𝗘 𝗣𝗔𝗣𝗔 𝗦𝗘 𝗟𝗔𝗗𝗘𝗚𝗔 𝗧𝗨",
    "𝗧𝗘𝗥𝗜 𝗕𝗘́𝗛𝗘𝗡 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧𝗛 𝗠𝗘 𝗕𝗢𝗠𝗕 𝗗𝗔𝗟𝗞𝗘 𝗨𝗗𝗔 𝗗𝗨𝗡𝗚𝗔 𝗠𝗔́𝗔̀𝗞𝗘 𝗟𝗔𝗪𝗗𝗘",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀𝗞𝗢 𝗧𝗥𝗔𝗜𝗡 𝗠𝗘 𝗟𝗘𝗝𝗔𝗞𝗘 𝗧𝗢𝗣 𝗕𝗘𝗗 𝗣𝗘 𝗟𝗜𝗧𝗔𝗞𝗘 𝗖𝗛𝗢𝗗 𝗗𝗨𝗡𝗚𝗔 𝗦𝗨𝗔𝗥 𝗞𝗘 𝗣𝗜𝗟𝗟𝗘 🤣🤣💋💋",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀𝗔𝗞𝗘 𝗡𝗨𝗗𝗘𝗦 𝗚𝗢𝗢𝗚𝗟𝗘 𝗣𝗘 𝗨𝗣𝗟𝗢𝗔𝗗 𝗞𝗔𝗥𝗗𝗨𝗡𝗚𝗔 𝗕𝗘́𝗛𝗘𝗡 𝗞𝗘 𝗟𝗔𝗘𝗪𝗗𝗘 👻🔥",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀𝗔𝗞𝗘 𝗡𝗨𝗗𝗘𝗦 𝗚𝗢𝗢𝗚𝗟𝗘 𝗣𝗘 𝗨𝗣𝗟𝗢𝗔𝗗 𝗞𝗔𝗥𝗗𝗨𝗡𝗚𝗔 𝗕𝗘́𝗛𝗘𝗡 𝗞𝗘 𝗟𝗔𝗘𝗪𝗗𝗘 👻🔥",
    "𝗧𝗘𝗥𝗜 𝗕𝗘́𝗛𝗘𝗡 𝗞𝗢 𝗖𝗛𝗢𝗗 𝗖𝗛𝗢𝗗𝗞𝗘 𝗩𝗜𝗗𝗘𝗢 𝗕𝗔𝗡𝗔𝗞𝗘 𝗫𝗡𝗫𝗫.𝗖𝗢𝗠 𝗣𝗘 𝗡𝗘𝗘𝗟𝗔𝗠 𝗞𝗔𝗥𝗗𝗨𝗡𝗚𝗔 𝗞𝗨𝗧𝗧𝗘 𝗞𝗘 𝗣𝗜𝗟𝗟𝗘 💦💋",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀𝗔𝗞𝗜 𝗖𝗛𝗨𝗗𝗔𝗜 𝗞𝗢 𝗣𝗢𝗥𝗡𝗛𝗨𝗕.𝗖𝗢𝗠 𝗣𝗘 𝗨𝗣𝗟𝗢𝗔𝗗 𝗞𝗔𝗥𝗗𝗨𝗡𝗚𝗔 𝗦𝗨𝗔𝗥 𝗞𝗘 𝗖𝗛𝗢𝗗𝗘 🤣💋💦",
    "𝗔𝗕𝗘 𝗧𝗘𝗥𝗜 𝗕𝗘́𝗛𝗘𝗡 𝗞𝗢 𝗖𝗛𝗢𝗗𝗨 𝗥Æ𝗡𝗗𝗜𝗞𝗘 𝗕𝗔𝗖𝗛𝗛𝗘 𝗧𝗘𝗥𝗘𝗞𝗢 𝗖𝗛𝗔𝗞𝗞𝗢 𝗦𝗘 𝗣𝗜𝗟𝗪𝗔𝗩𝗨𝗡𝗚𝗔 𝗥Æ𝗡𝗗𝗜𝗞𝗘 𝗕𝗔𝗖𝗛𝗛𝗘 🤣🤣",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧𝗛 𝗙𝗔𝗔𝗗𝗞𝗘 𝗥𝗔𝗞𝗗𝗜𝗔 𝗠𝗔́𝗔̀𝗞𝗘 𝗟𝗢𝗗𝗘 𝗝𝗔𝗔 𝗔𝗕𝗕 𝗦𝗜𝗟𝗪𝗔𝗟𝗘 👄👄",
    "𝗧𝗘𝗥𝗜 𝗕𝗘́𝗛𝗘𝗡 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧𝗛 𝗠𝗘 𝗠𝗘𝗥𝗔 𝗟𝗨𝗡𝗗 𝗞𝗔𝗔𝗟𝗔",
    "𝗧𝗘𝗥𝗜 𝗕𝗘́𝗛𝗘𝗡 𝗟𝗘𝗧𝗜 𝗠𝗘𝗥𝗜 𝗟𝗨𝗡𝗗 𝗕𝗔𝗗𝗘 𝗠𝗔𝗦𝗧𝗜 𝗦𝗘 𝗧𝗘𝗥𝗜 𝗕𝗘́𝗛𝗘𝗡 𝗞𝗢 𝗠𝗘𝗡𝗘 𝗖𝗛𝗢𝗗 𝗗𝗔𝗟𝗔 𝗕𝗢𝗛𝗢𝗧 𝗦𝗔𝗦𝗧𝗘 𝗦𝗘",
    "𝗕𝗘𝗧𝗘 𝗧𝗨 𝗕𝗔𝗔𝗣 𝗦𝗘 𝗟𝗘𝗚𝗔 𝗣𝗔𝗡𝗚𝗔 𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀𝗔 𝗞𝗢 𝗖𝗛𝗢𝗗 𝗗𝗨𝗡𝗚𝗔 𝗞𝗔𝗥𝗞𝗘 𝗡𝗔𝗡𝗚𝗔 💦💋",
    "𝗛𝗔𝗛𝗔𝗛𝗔𝗛 𝗠𝗘𝗥𝗘 𝗕𝗘𝗧𝗘 𝗔𝗚𝗟𝗜 𝗕𝗔𝗔𝗥 𝗔𝗣𝗡𝗜 𝗠𝗔́𝗔̀𝗞𝗢 𝗟𝗘𝗞𝗘 𝗔𝗔𝗬𝗔 𝗠𝗔𝗧𝗛 𝗞𝗔𝗧 𝗢𝗥 𝗠𝗘𝗥𝗘 𝗠𝗢𝗧𝗘 𝗟𝗨𝗡𝗗 𝗦𝗘 𝗖𝗛𝗨𝗗𝗪𝗔𝗬𝗔 𝗠𝗔𝗧𝗛 𝗞𝗔𝗥",
    "𝗖𝗛𝗔𝗟 𝗕𝗘𝗧𝗔 𝗧𝗨𝗝𝗛𝗘 𝗠𝗔́𝗔̀𝗙 𝗞𝗜𝗔 🤣 𝗔𝗕𝗕 𝗔𝗣𝗡𝗜 𝗚𝗙 𝗞𝗢 𝗕𝗛𝗘𝗝",
    "𝗦𝗛𝗔𝗥𝗔𝗠 𝗞𝗔𝗥 𝗧𝗘𝗥𝗜 𝗕𝗘́𝗛𝗘𝗡 𝗞𝗔 𝗕𝗛𝗢𝗦𝗗𝗔 𝗞𝗜𝗧𝗡𝗔 𝗚𝗔𝗔𝗟𝗜𝗔 𝗦𝗨𝗡𝗪𝗔𝗬𝗘𝗚𝗔 𝗔𝗣𝗡𝗜 𝗠𝗔́𝗔̀𝗔 𝗕𝗘́𝗛𝗘𝗡 𝗞𝗘 𝗨𝗣𝗘𝗥",
    "𝗔𝗕𝗘 𝗥Æ𝗡𝗗𝗜𝗞𝗘 𝗕𝗔𝗖𝗛𝗛𝗘 𝗔𝗨𝗞𝗔𝗧 𝗡𝗛𝗜 𝗛𝗘𝗧𝗢 𝗔𝗣𝗡𝗜 𝗥Æ𝗡𝗗𝗜 𝗠𝗔́𝗔̀𝗞𝗢 𝗟𝗘𝗞𝗘 𝗔𝗔𝗬𝗔 𝗠𝗔𝗧𝗛 𝗞𝗔𝗥 𝗛𝗔𝗛𝗔𝗛𝗔𝗛𝗔",
    "𝗞𝗜𝗗𝗭 𝗠𝗔̂𝗔̂𝗗𝗔𝗥𝗖𝗛Ø𝗗 𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀𝗞𝗢 𝗖𝗛𝗢𝗗 𝗖𝗛𝗢𝗗𝗞𝗘 𝗧𝗘𝗥𝗥 𝗟𝗜𝗬𝗘 𝗕𝗛𝗔𝗜 𝗗𝗘𝗗𝗜𝗬𝗔",
    "𝗝𝗨𝗡𝗚𝗟𝗘 𝗠𝗘 𝗡𝗔𝗖𝗛𝗧𝗔 𝗛𝗘 𝗠𝗢𝗥𝗘 𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀𝗞𝗜 𝗖𝗛𝗨𝗗𝗔𝗜 𝗗𝗘𝗞𝗞𝗘 𝗦𝗔𝗕 𝗕𝗢𝗟𝗧𝗘 𝗢𝗡𝗖𝗘 𝗠𝗢𝗥𝗘 𝗢𝗡𝗖𝗘 𝗠𝗢𝗥𝗘 🤣🤣💦💋",
    "𝗚𝗔𝗟𝗜 𝗚𝗔𝗟𝗜 𝗠𝗘 𝗥𝗘𝗛𝗧𝗔 𝗛𝗘 𝗦𝗔𝗡𝗗 𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀𝗞𝗢 𝗖𝗛𝗢𝗗 𝗗𝗔𝗟𝗔 𝗢𝗥 𝗕𝗔𝗡𝗔 𝗗𝗜𝗔 𝗥𝗔𝗡𝗗 🤤🤣",
    "𝗦𝗔𝗕 𝗕𝗢𝗟𝗧𝗘 𝗠𝗨𝗝𝗛𝗞𝗢 𝗣𝗔𝗣𝗔 𝗞𝗬𝗢𝗨𝗡𝗞𝗜 𝗠𝗘𝗡𝗘 𝗕𝗔𝗡𝗔𝗗𝗜𝗔 𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀𝗞𝗢 𝗣𝗥𝗘𝗚𝗡𝗘𝗡𝗧 🤣🤣",
    "𝗦𝗨𝗔𝗥 𝗞𝗘 𝗣𝗜𝗟𝗟𝗘 𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧𝗛 𝗠𝗘 𝗦𝗨𝗔𝗥 𝗞𝗔 𝗟𝗢𝗨𝗗𝗔 𝗢𝗥 𝗧𝗘𝗥𝗜 𝗕𝗘́𝗛𝗘𝗡 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧𝗛 𝗠𝗘 𝗠𝗘𝗥𝗔 𝗟𝗢𝗗𝗔",
    "𝗖𝗛𝗔𝗟 𝗖𝗛𝗔𝗟 𝗔𝗣𝗡𝗜 𝗠𝗔́𝗔̀𝗞𝗜 𝗖𝗛𝗨𝗖𝗛𝗜𝗬𝗔 𝗗𝗜𝗞𝗔",
    "𝗛𝗔𝗛𝗔𝗛𝗔𝗛𝗔 𝗕𝗔𝗖𝗛𝗛𝗘 𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀𝗔𝗞𝗢 𝗖𝗛𝗢𝗗 𝗗𝗜𝗔 𝗡𝗔𝗡𝗚𝗔 𝗞𝗔𝗥𝗞𝗘",
    "𝗧𝗘𝗥𝗜 𝗚𝗙 𝗛𝗘 𝗕𝗔𝗗𝗜 𝗦𝗘𝗫𝗬 𝗨𝗦𝗞𝗢 𝗣𝗜𝗟𝗔𝗞𝗘 𝗖𝗛𝗢𝗢𝗗𝗘𝗡𝗚𝗘 𝗣𝗘𝗣𝗦𝗜",
    "2 𝗥𝗨𝗣𝗔𝗬 𝗞𝗜 𝗣𝗘𝗣𝗦𝗜 𝗧𝗘𝗥𝗜 𝗠𝗨𝗠𝗠𝗬 𝗦𝗔𝗕𝗦𝗘 𝗦𝗘𝗫𝗬 💋💦",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀𝗞𝗢 𝗖𝗛𝗘𝗘𝗠𝗦 𝗦𝗘 𝗖𝗛𝗨𝗗𝗪𝗔𝗩𝗨𝗡𝗚𝗔 𝗠𝗔𝗗𝗘𝗥𝗖𝗛𝗢𝗢𝗗 𝗞𝗘 𝗣𝗜𝗟𝗟𝗘 💦🤣",
    "𝗧𝗘𝗥𝗜 𝗕𝗘́𝗛𝗘𝗡 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧𝗛 𝗠𝗘 𝗠𝗨𝗧𝗛𝗞𝗘 𝗙𝗔𝗥𝗔𝗥 𝗛𝗢𝗝𝗔𝗩𝗨𝗡𝗚𝗔 𝗛𝗨𝗜 𝗛𝗨𝗜 𝗛𝗨𝗜",
    "𝗦𝗣𝗘𝗘𝗗 𝗟𝗔𝗔𝗔 𝗧𝗘𝗥𝗜 𝗕𝗘́𝗛𝗘𝗡 𝗖𝗛𝗢𝗗𝗨 𝗥Æ𝗡𝗗𝗜𝗞𝗘 𝗣𝗜𝗟𝗟𝗘 💋💦🤣",
    "𝗔𝗥𝗘 𝗥𝗘 𝗠𝗘𝗥𝗘 𝗕𝗘𝗧𝗘 𝗞𝗬𝗢𝗨𝗡 𝗦𝗣𝗘𝗘𝗗 𝗣𝗔𝗞𝗔𝗗 𝗡𝗔 𝗣𝗔𝗔𝗔 𝗥𝗔𝗛𝗔 𝗔𝗣𝗡𝗘 𝗕𝗔𝗔𝗣 𝗞𝗔 𝗛𝗔𝗛𝗔𝗛🤣🤣",
    "𝗦𝗨𝗡 𝗦𝗨𝗡 𝗦𝗨𝗔𝗥 𝗞𝗘 𝗣𝗜𝗟𝗟𝗘 𝗝𝗛𝗔𝗡𝗧𝗢 𝗞𝗘 𝗦𝗢𝗨𝗗𝗔𝗚𝗔𝗥 𝗔𝗣𝗡𝗜 𝗠𝗨𝗠𝗠𝗬 𝗞𝗜 𝗡𝗨𝗗𝗘𝗦 𝗕𝗛𝗘𝗝",
    "𝗔𝗕𝗘 𝗦𝗨𝗡 𝗟𝗢𝗗𝗘 𝗧𝗘𝗥𝗜 𝗕𝗘́𝗛𝗘𝗡 𝗞𝗔 𝗕𝗛𝗢𝗦𝗗𝗔 𝗙𝗔𝗔𝗗 𝗗𝗨𝗡𝗚𝗔",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀𝗞𝗢 𝗞𝗛𝗨𝗟𝗘 𝗕𝗔𝗝𝗔𝗥 𝗠𝗘 𝗖𝗛𝗢𝗗 𝗗𝗔𝗟𝗔 🤣🤣💋",
    "𝐌𝐀𝐃𝐀𝐑𝐂𝐇𝐎𝐃 𝐓𝐄𝐑𝐈 𝐌𝐀𝐀 𝐊𝐈 𝐂𝐇𝐔𝐓 𝐌𝐄 𝐆𝐇𝐔𝐓𝐊𝐀 𝐊𝐇𝐀𝐀𝐊𝐄 𝐓𝐇𝐎𝐎𝐊 𝐃𝐔𝐍𝐆𝐀 🤣🤣",
    "𝐓𝐄𝐑𝐄 𝐁𝐄𝐇𝐄𝐍 𝐊 𝐂𝐇𝐔𝐓 𝐌𝐄 𝐂𝐇𝐀𝐊𝐔 𝐃𝐀𝐀𝐋 𝐊𝐀𝐑 𝐂𝐇𝐔𝐓 𝐊𝐀 𝐊𝐇𝐎𝐎𝐍 𝐊𝐀𝐑 𝐃𝐔𝐆𝐀", 
    "𝐓𝐄𝐑𝐈 𝐕𝐀𝐇𝐄𝐄𝐍 𝐍𝐇𝐈 𝐇𝐀𝐈 𝐊𝐘𝐀? 𝟗 𝐌𝐀𝐇𝐈𝐍𝐄 𝐑𝐔𝐊 𝐒𝐀𝐆𝐈 𝐕𝐀𝐇𝐄𝐄𝐍 𝐃𝐄𝐓𝐀 𝐇𝐔 🤣🤣🤩", 
    "𝐓𝐄𝐑𝐈 𝐌𝐀𝐀 𝐊 𝐁𝐇𝐎𝐒𝐃𝐄 𝐌𝐄 𝐀𝐄𝐑𝐎𝐏𝐋𝐀𝐍𝐄𝐏𝐀𝐑𝐊 𝐊𝐀𝐑𝐊𝐄 𝐔𝐃𝐀𝐀𝐍 𝐁𝐇𝐀𝐑 𝐃𝐔𝐆𝐀 ✈️🛫", 
    "𝐓𝐄𝐑𝐈 𝐌𝐀𝐀 𝐊𝐈 𝐂𝐇𝐔𝐓 𝐌𝐄 𝐒𝐔𝐓𝐋𝐈 𝐁𝐎𝐌𝐁 𝐅𝐎𝐃 𝐃𝐔𝐍𝐆𝐀 𝐓𝐄𝐑𝐈 𝐌𝐀𝐀 𝐊𝐈 𝐉𝐇𝐀𝐀𝐓𝐄 𝐉𝐀𝐋 𝐊𝐄 𝐊𝐇𝐀𝐀𝐊 𝐇𝐎 𝐉𝐀𝐘𝐄𝐆𝐈💣", 
    "𝐓𝐄𝐑𝐈 𝐌𝐀𝐀𝐊𝐈 𝐂𝐇𝐔𝐓 𝐌𝐄 𝐒𝐂𝐎𝐎𝐓𝐄𝐑 𝐃𝐀𝐀𝐋 𝐃𝐔𝐆𝐀👅", 
    "𝐓𝐄𝐑𝐄 𝐁𝐄𝐇𝐄𝐍 𝐊 𝐂𝐇𝐔𝐓 𝐌𝐄 𝐂𝐇𝐀𝐊𝐔 𝐃𝐀𝐀𝐋 𝐊𝐀𝐑 𝐂𝐇𝐔𝐓 𝐊𝐀 𝐊𝐇𝐎𝐎𝐍 𝐊𝐀𝐑 𝐃𝐔𝐆𝐀", 
    "𝐓𝐄𝐑𝐄 𝐁𝐄𝐇𝐄𝐍 𝐊 𝐂𝐇𝐔𝐓 𝐌𝐄 𝐂𝐇𝐀𝐊𝐔 𝐃𝐀𝐀𝐋 𝐊𝐀𝐑 𝐂𝐇𝐔𝐓 𝐊𝐀 𝐊𝐇𝐎𝐎𝐍 𝐊𝐀𝐑 𝐃𝐔𝐆𝐀", 
    "𝐓𝐄𝐑𝐈 𝐌𝐀𝐀 𝐊𝐈 𝐂𝐇𝐔𝐓 𝐊𝐀𝐊𝐓𝐄 🤱 𝐆𝐀𝐋𝐈 𝐊𝐄 𝐊𝐔𝐓𝐓𝐎 🦮 𝐌𝐄 𝐁𝐀𝐀𝐓 𝐃𝐔𝐍𝐆𝐀 𝐏𝐇𝐈𝐑 🍞 𝐁𝐑𝐄𝐀𝐃 𝐊𝐈 𝐓𝐀𝐑𝐇 𝐊𝐇𝐀𝐘𝐄𝐍𝐆𝐄 𝐖𝐎 𝐓𝐄𝐑𝐈 𝐌𝐀𝐀 𝐊𝐈 𝐂𝐇𝐔𝐓", 
    "𝐃𝐔𝐃𝐇 𝐇𝐈𝐋𝐀𝐀𝐔𝐍𝐆𝐀 𝐓𝐄𝐑𝐈 𝐕𝐀𝐇𝐄𝐄𝐍 𝐊𝐄 𝐔𝐏𝐑 𝐍𝐈𝐂𝐇𝐄 🆙🆒😙", 
    "𝐓𝐄𝐑𝐈 𝐌𝐀𝐀 𝐊𝐈 𝐂𝐇𝐔𝐓 𝐌𝐄 ✋ 𝐇𝐀𝐓𝐓𝐇 𝐃𝐀𝐋𝐊𝐄 👶 𝐁𝐀𝐂𝐂𝐇𝐄 𝐍𝐈𝐊𝐀𝐋 𝐃𝐔𝐍𝐆𝐀 😍", 
    "𝐓𝐄𝐑𝐈 𝐁𝐄𝐇𝐍 𝐊𝐈 𝐂𝐇𝐔𝐓 𝐌𝐄 𝐊𝐄𝐋𝐄 𝐊𝐄 𝐂𝐇𝐈𝐋𝐊𝐄 🍌🍌😍", 
    "𝐓𝐄𝐑𝐈 𝐁𝐇𝐄𝐍 𝐊𝐈 𝐂𝐇𝐔𝐓 𝐌𝐄 𝐔𝐒𝐄𝐑𝐁𝐎𝐓 𝐋𝐀𝐆𝐀𝐀𝐔𝐍𝐆𝐀 𝐒𝐀𝐒𝐓𝐄 𝐒𝐏𝐀𝐌 𝐊𝐄 𝐂𝐇𝐎𝐃𝐄", 
    "𝐓𝐄𝐑𝐈 𝐕𝐀𝐇𝐄𝐄𝐍 𝐃𝐇𝐀𝐍𝐃𝐇𝐄 𝐕𝐀𝐀𝐋𝐈 😋😛", 
    "𝐓𝐄𝐑𝐈 𝐌𝐀𝐀 𝐊𝐄 𝐁𝐇𝐎𝐒𝐃𝐄 𝐌𝐄 𝐀𝐂 𝐋𝐀𝐆𝐀 𝐃𝐔𝐍𝐆𝐀 𝐒𝐀𝐀𝐑𝐈 𝐆𝐀𝐑𝐌𝐈 𝐍𝐈𝐊𝐀𝐋 𝐉𝐀𝐀𝐘𝐄𝐆𝐈", 
    "𝐓𝐄𝐑𝐈 𝐕𝐀𝐇𝐄𝐄𝐍 𝐊𝐎 𝐇𝐎𝐑𝐋𝐈𝐂𝐊𝐒 𝐏𝐄𝐄𝐋𝐀𝐔𝐍𝐆𝐀 𝐌𝐀𝐃𝐀𝐑𝐂𝐇𝐎𝐃😚", 
    "𝐓𝐄𝐑𝐈 𝐌𝐀𝐀 𝐊𝐈 𝐆𝐀𝐀𝐍𝐃 𝐌𝐄 𝐒𝐀𝐑𝐈𝐘𝐀 𝐃𝐀𝐀𝐋 𝐃𝐔𝐍𝐆𝐀 𝐌𝐀𝐃𝐀𝐑𝐂𝐇𝐎𝐃 𝐔𝐒𝐈 𝐒𝐀𝐑𝐈𝐘𝐄 𝐏𝐑 𝐓𝐀𝐍𝐆 𝐊𝐄 𝐁𝐀𝐂𝐇𝐄 𝐏𝐀𝐈𝐃𝐀 𝐇𝐎𝐍𝐆𝐄 😱😱", 
    "𝐓𝐄𝐑𝐈 𝐌𝐀𝐀 𝐊𝐎 𝐊𝐎𝐋𝐊𝐀𝐓𝐀 𝐕𝐀𝐀𝐋𝐄 𝐉𝐈𝐓𝐔 𝐁𝐇𝐀𝐈𝐘𝐀 𝐊𝐀 𝐋𝐔𝐍𝐃 𝐌𝐔𝐁𝐀𝐑𝐀𝐊 🤩🤩", 
    "𝐓𝐄𝐑𝐈 𝐌𝐔𝐌𝐌𝐘 𝐊𝐈 𝐅𝐀𝐍𝐓𝐀𝐒𝐘 𝐇𝐔 𝐋𝐀𝐖𝐃𝐄, 𝐓𝐔 𝐀𝐏𝐍𝐈 𝐁𝐇𝐄𝐍 𝐊𝐎 𝐒𝐌𝐁𝐇𝐀𝐀𝐋 😈😈", 
    "𝐓𝐄𝐑𝐀 𝐏𝐄𝐇𝐋𝐀 𝐁𝐀𝐀𝐏 𝐇𝐔 𝐌𝐀𝐃𝐀𝐑𝐂𝐇𝐎𝐃 ", 
    "𝐓𝐄𝐑𝐈 𝐕𝐀𝐇𝐄𝐄𝐍 𝐊𝐄 𝐁𝐇𝐎𝐒𝐃𝐄 𝐌𝐄 𝐗𝐕𝐈𝐃𝐄𝐎𝐒.𝐂𝐎𝐌 𝐂𝐇𝐀𝐋𝐀 𝐊𝐄 𝐌𝐔𝐓𝐇 𝐌𝐀𝐀𝐑𝐔𝐍𝐆𝐀 🤡😹", 
    "𝐓𝐄𝐑𝐈 𝐌𝐀𝐀 𝐊𝐀 𝐆𝐑𝐎𝐔𝐏 𝐕𝐀𝐀𝐋𝐎𝐍 𝐒𝐀𝐀𝐓𝐇 𝐌𝐈𝐋𝐊𝐄 𝐆𝐀𝐍𝐆 𝐁𝐀𝐍𝐆 𝐊𝐑𝐔𝐍𝐆𝐀🙌🏻☠️ ", 
    "𝐓𝐄𝐑𝐈 𝐈𝐓𝐄𝐌 𝐊𝐈 𝐆𝐀𝐀𝐍𝐃 𝐌𝐄 𝐋𝐔𝐍𝐃 𝐃𝐀𝐀𝐋𝐊𝐄,𝐓𝐄𝐑𝐄 𝐉𝐀𝐈𝐒𝐀 𝐄𝐊 𝐎𝐑 𝐍𝐈𝐊𝐀𝐀𝐋 𝐃𝐔𝐍𝐆𝐀 𝐌𝐀𝐃𝐀𝐑𝐂𝐇𝐎𝐃🤘🏻🙌🏻☠️ ", 
    "𝐀𝐔𝐊𝐀𝐀𝐓 𝐌𝐄 𝐑𝐄𝐇 𝐕𝐑𝐍𝐀 𝐆𝐀𝐀𝐍𝐃 𝐌𝐄 𝐃𝐀𝐍𝐃𝐀 𝐃𝐀𝐀𝐋 𝐊𝐄 𝐌𝐔𝐇 𝐒𝐄 𝐍𝐈𝐊𝐀𝐀𝐋 𝐃𝐔𝐍𝐆𝐀 𝐒𝐇𝐀𝐑𝐈𝐑 𝐁𝐇𝐈 𝐃𝐀𝐍𝐃𝐄 𝐉𝐄𝐒𝐀 𝐃𝐈𝐊𝐇𝐄𝐆𝐀 🙄🤭🤭", 
    "𝐓𝐄𝐑𝐈 𝐌𝐔𝐌𝐌𝐘 𝐊𝐄 𝐒𝐀𝐀𝐓𝐇 𝐋𝐔𝐃𝐎 𝐊𝐇𝐄𝐋𝐓𝐄 𝐊𝐇𝐄𝐋𝐓𝐄 𝐔𝐒𝐊𝐄 𝐌𝐔𝐇 𝐌𝐄 𝐀𝐏𝐍𝐀 𝐋𝐎𝐃𝐀 𝐃𝐄 𝐃𝐔𝐍𝐆𝐀☝🏻☝🏻😬", 
    "𝐓𝐄𝐑𝐈 𝐕𝐀𝐇𝐄𝐄𝐍 𝐊𝐎 𝐀𝐏𝐍𝐄 𝐋𝐔𝐍𝐃 𝐏𝐑 𝐈𝐓𝐍𝐀 𝐉𝐇𝐔𝐋𝐀𝐀𝐔𝐍𝐆𝐀 𝐊𝐈 𝐉𝐇𝐔𝐋𝐓𝐄 𝐉𝐇𝐔𝐋𝐓𝐄 𝐇𝐈 𝐁𝐀𝐂𝐇𝐀 𝐏𝐀𝐈𝐃𝐀 𝐊𝐑 𝐃𝐄𝐆𝐈👀👯 ", 
    "𝐓𝐄𝐑𝐈 𝐌𝐀𝐀 𝐊𝐈 𝐂𝐇𝐔𝐓 𝐌𝐄𝐈 𝐁𝐀𝐓𝐓𝐄𝐑𝐘 𝐋𝐀𝐆𝐀 𝐊𝐄 𝐏𝐎𝐖𝐄𝐑𝐁𝐀𝐍𝐊 𝐁𝐀𝐍𝐀 𝐃𝐔𝐍𝐆𝐀 🔋 🔥🤩", 
    "𝐓𝐄𝐑𝐈 𝐌𝐀𝐀 𝐊𝐈 𝐂𝐇𝐔𝐓 𝐌𝐄𝐈 𝐂++ 𝐒𝐓𝐑𝐈𝐍𝐆 𝐄𝐍𝐂𝐑𝐘𝐏𝐓𝐈𝐎𝐍 𝐋𝐀𝐆𝐀 𝐃𝐔𝐍𝐆𝐀 𝐁𝐀𝐇𝐓𝐈 𝐇𝐔𝐘𝐈 𝐂𝐇𝐔𝐓 𝐑𝐔𝐊 𝐉𝐀𝐘𝐄𝐆𝐈𝐈𝐈𝐈😈🔥😍", 
    "𝐓𝐄𝐑𝐈 𝐌𝐀𝐀 𝐊𝐄 𝐆𝐀𝐀𝐍𝐃 𝐌𝐄𝐈 𝐉𝐇𝐀𝐀𝐃𝐔 𝐃𝐀𝐋 𝐊𝐄 𝐌𝐎𝐑 🦚 𝐁𝐀𝐍𝐀 𝐃𝐔𝐍𝐆𝐀𝐀 🤩🥵😱", 
    "𝐓𝐄𝐑𝐈 𝐂𝐇𝐔𝐓 𝐊𝐈 𝐂𝐇𝐔𝐓 𝐌𝐄𝐈 𝐒𝐇𝐎𝐔𝐋𝐃𝐄𝐑𝐈𝐍𝐆 𝐊𝐀𝐑 𝐃𝐔𝐍𝐆𝐀𝐀 𝐇𝐈𝐋𝐀𝐓𝐄 𝐇𝐔𝐘𝐄 𝐁𝐇𝐈 𝐃𝐀𝐑𝐃 𝐇𝐎𝐆𝐀𝐀𝐀😱🤮👺", 
    "𝐓𝐄𝐑𝐈 𝐌𝐀𝐀 𝐊𝐎 𝐑𝐄𝐃𝐈 𝐏𝐄 𝐁𝐀𝐈𝐓𝐇𝐀𝐋 𝐊𝐄 𝐔𝐒𝐒𝐄 𝐔𝐒𝐊𝐈 𝐂𝐇𝐔𝐓 𝐁𝐈𝐋𝐖𝐀𝐔𝐍𝐆𝐀𝐀 💰 😵🤩", 
    "𝐁𝐇𝐎𝐒𝐃𝐈𝐊𝐄 𝐓𝐄𝐑𝐈 𝐌𝐀𝐀 𝐊𝐈 𝐂𝐇𝐔𝐓 𝐌𝐄𝐈 𝟒 𝐇𝐎𝐋𝐄 𝐇𝐀𝐈 𝐔𝐍𝐌𝐄 𝐌𝐒𝐄𝐀𝐋 𝐋𝐀𝐆𝐀 𝐁𝐀𝐇𝐔𝐓 𝐁𝐀𝐇𝐄𝐓𝐈 𝐇𝐀𝐈 𝐁𝐇𝐎𝐅𝐃𝐈𝐊𝐄👊🤮🤢🤢", 
    "𝐓𝐄𝐑𝐈 𝐁𝐀𝐇𝐄𝐍 𝐊𝐈 𝐂𝐇𝐔𝐓 𝐌𝐄𝐈 𝐁𝐀𝐑𝐆𝐀𝐃 𝐊𝐀 𝐏𝐄𝐃 𝐔𝐆𝐀 𝐃𝐔𝐍𝐆𝐀𝐀 𝐂𝐎𝐑𝐎𝐍𝐀 𝐌𝐄𝐈 𝐒𝐀𝐁 𝐎𝐗𝐘𝐆𝐄𝐍 𝐋𝐄𝐊𝐀𝐑 𝐉𝐀𝐘𝐄𝐍𝐆𝐄🤢🤩🥳", 
    "𝐓𝐄𝐑𝐈 𝐌𝐀𝐀 𝐊𝐈 𝐂𝐇𝐔𝐓 𝐌𝐄𝐈 𝐒𝐔𝐃𝐎 𝐋𝐀𝐆𝐀 𝐊𝐄 𝐁𝐈𝐆𝐒𝐏𝐀𝐌 𝐋𝐀𝐆𝐀 𝐊𝐄 𝟗𝟗𝟗𝟗 𝐅𝐔𝐂𝐊 𝐋𝐀𝐆𝐀𝐀 𝐃𝐔 🤩🥳🔥", 
    "𝐓𝐄𝐑𝐈 𝐕𝐀𝐇𝐄𝐍 𝐊𝐄 𝐁𝐇𝐎𝐒𝐃𝐈𝐊𝐄 𝐌𝐄𝐈 𝐁𝐄𝐒𝐀𝐍 𝐊𝐄 𝐋𝐀𝐃𝐃𝐔 𝐁𝐇𝐀𝐑 𝐃𝐔𝐍𝐆𝐀🤩🥳🔥😈", 
    "𝐓𝐄𝐑𝐈 𝐌𝐀𝐀 𝐊𝐈 𝐂𝐇𝐔𝐓 𝐊𝐇𝐎𝐃 𝐊𝐄 𝐔𝐒𝐌𝐄 𝐂𝐘𝐋𝐈𝐍𝐃𝐄𝐑 ⛽️ 𝐅𝐈𝐓 𝐊𝐀𝐑𝐊𝐄 𝐔𝐒𝐌𝐄𝐄 𝐃𝐀𝐋 𝐌𝐀𝐊𝐇𝐀𝐍𝐈 𝐁𝐀𝐍𝐀𝐔𝐍𝐆𝐀𝐀𝐀🤩👊🔥", 
    "𝐓𝐄𝐑𝐈 𝐌𝐀𝐀 𝐊𝐈 𝐂𝐇𝐔𝐓 𝐌𝐄𝐈 𝐒𝐇𝐄𝐄𝐒𝐇𝐀 𝐃𝐀𝐋 𝐃𝐔𝐍𝐆𝐀𝐀𝐀 𝐀𝐔𝐑 𝐂𝐇𝐀𝐔𝐑𝐀𝐇𝐄 𝐏𝐄 𝐓𝐀𝐀𝐍𝐆 𝐃𝐔𝐍𝐆𝐀 𝐁𝐇𝐎𝐒𝐃𝐈𝐊𝐄😈😱🤩", 
    "𝐓𝐄𝐑𝐈 𝐌𝐀𝐀 𝐊𝐈 𝐂𝐇𝐔𝐓 𝐌𝐄𝐈 𝐂𝐑𝐄𝐃𝐈𝐓 𝐂𝐀𝐑𝐃 𝐃𝐀𝐋 𝐊𝐄 𝐀𝐆𝐄 𝐒𝐄 𝟓𝟎𝟎 𝐊𝐄 𝐊𝐀𝐀𝐑𝐄 𝐊𝐀𝐀𝐑𝐄 𝐍𝐎𝐓𝐄 𝐍𝐈𝐊𝐀𝐋𝐔𝐍𝐆𝐀𝐀 𝐁𝐇𝐎𝐒𝐃𝐈𝐊𝐄💰💰🤩", 
    "𝐓𝐄𝐑𝐈 𝐌𝐀𝐀 𝐊𝐄 𝐒𝐀𝐓𝐇 𝐒𝐔𝐀𝐑 𝐊𝐀 𝐒𝐄𝐗 𝐊𝐀𝐑𝐖𝐀 𝐃𝐔𝐍𝐆𝐀𝐀 𝐄𝐊 𝐒𝐀𝐓𝐇 𝟔-𝟔 𝐁𝐀𝐂𝐇𝐄 𝐃𝐄𝐆𝐈💰🔥😱", 
    "𝐓𝐄𝐑𝐈 𝐁𝐀𝐇𝐄𝐍 𝐊𝐈 𝐂𝐇𝐔𝐓 𝐌𝐄𝐈 𝐀𝐏𝐏𝐋𝐄 𝐊𝐀 𝟏𝟖𝐖 𝐖𝐀𝐋𝐀 𝐂𝐇𝐀𝐑𝐆𝐄𝐑 🔥🤩", 
    "𝐓𝐄𝐑𝐈 𝐁𝐀𝐇𝐄𝐍 𝐊𝐈 𝐆𝐀𝐀𝐍𝐃 𝐌𝐄𝐈 𝐎𝐍𝐄𝐏𝐋𝐔𝐒 𝐊𝐀 𝐖𝐑𝐀𝐏 𝐂𝐇𝐀𝐑𝐆𝐄𝐑 𝟑𝟎𝐖 𝐇𝐈𝐆𝐇 𝐏𝐎𝐖𝐄𝐑 💥😂😎", 
    "𝐓𝐄𝐑𝐈 𝐁𝐀𝐇𝐄𝐍 𝐊𝐈 𝐂𝐇𝐔𝐓 𝐊𝐎 𝐀𝐌𝐀𝐙𝐎𝐍 𝐒𝐄 𝐎𝐑𝐃𝐄𝐑 𝐊𝐀𝐑𝐔𝐍𝐆𝐀 𝟏𝟎 𝐫𝐬 𝐌𝐄𝐈 𝐀𝐔𝐑 𝐅𝐋𝐈𝐏𝐊𝐀𝐑𝐓 𝐏𝐄 𝟐𝟎 𝐑𝐒 𝐌𝐄𝐈 𝐁𝐄𝐂𝐇 𝐃𝐔𝐍𝐆𝐀🤮👿😈🤖", 
    "𝐓𝐄𝐑𝐈 𝐌𝐀𝐀 𝐊𝐈 𝐁𝐀𝐃𝐈 𝐁𝐇𝐔𝐍𝐃 𝐌𝐄 𝐙𝐎𝐌𝐀𝐓𝐎 𝐃𝐀𝐋 𝐊𝐄 𝐒𝐔𝐁𝐖𝐀𝐘 𝐊𝐀 𝐁𝐅𝐅 𝐕𝐄𝐆 𝐒𝐔𝐁 𝐂𝐎𝐌𝐁𝐎 [𝟏𝟓𝐜𝐦 , 𝟏𝟔 𝐢𝐧𝐜𝐡𝐞𝐬 ] 𝐎𝐑𝐃𝐄𝐑 𝐂𝐎𝐃 𝐊𝐑𝐕𝐀𝐔𝐍𝐆𝐀 𝐎𝐑 𝐓𝐄𝐑𝐈 𝐌𝐀𝐀 𝐉𝐀𝐁 𝐃𝐈𝐋𝐈𝐕𝐄𝐑𝐘 𝐃𝐄𝐍𝐄 𝐀𝐘𝐄𝐆𝐈 𝐓𝐀𝐁 𝐔𝐒𝐏𝐄 𝐉𝐀𝐀𝐃𝐔 𝐊𝐑𝐔𝐍𝐆𝐀 𝐎𝐑 𝐅𝐈𝐑 𝟗 𝐌𝐎𝐍𝐓𝐇 𝐁𝐀𝐀𝐃 𝐕𝐎 𝐄𝐊 𝐎𝐑 𝐅𝐑𝐄𝐄 𝐃𝐈𝐋𝐈𝐕𝐄𝐑𝐘 𝐃𝐄𝐆𝐈🙀👍🥳🔥", 
    "𝐓𝐄𝐑𝐈 𝐁𝐇𝐄𝐍 𝐊𝐈 𝐂𝐇𝐔𝐓 𝐊𝐀𝐀𝐋𝐈🙁🤣💥", 
    "𝐓𝐄𝐑𝐈 𝐌𝐀𝐀 𝐊𝐈 𝐂𝐇𝐔𝐓 𝐌𝐄 𝐂𝐇𝐀𝐍𝐆𝐄𝐒 𝐂𝐎𝐌𝐌𝐈𝐓 𝐊𝐑𝐔𝐆𝐀 𝐅𝐈𝐑 𝐓𝐄𝐑𝐈 𝐁𝐇𝐄𝐄𝐍 𝐊𝐈 𝐂𝐇𝐔𝐓 𝐀𝐔𝐓𝐎𝐌𝐀𝐓𝐈𝐂𝐀𝐋𝐋𝐘 𝐔𝐏𝐃𝐀𝐓𝐄 𝐇𝐎𝐉𝐀𝐀𝐘𝐄𝐆𝐈🤖🙏🤔", 
    "𝐓𝐄𝐑𝐈 𝐌𝐀𝐔𝐒𝐈 𝐊𝐄 𝐁𝐇𝐎𝐒𝐃𝐄 𝐌𝐄𝐈 𝐈𝐍𝐃𝐈𝐀𝐍 𝐑𝐀𝐈𝐋𝐖𝐀𝐘 🚂💥😂", 
    "𝐓𝐔 𝐓𝐄𝐑𝐈 𝐁𝐀𝐇𝐄𝐍 𝐓𝐄𝐑𝐀 𝐊𝐇𝐀𝐍𝐃𝐀𝐍 𝐒𝐀𝐁 𝐁𝐀𝐇𝐄𝐍 𝐊𝐄 𝐋𝐀𝐖𝐃𝐄 𝐑𝐀𝐍𝐃𝐈 𝐇𝐀𝐈 𝐑𝐀𝐍𝐃𝐈 🤢✅🔥", 
    "𝐓𝐄𝐑𝐈 𝐁𝐀𝐇𝐄𝐍 𝐊𝐈 𝐂𝐇𝐔𝐓 𝐌𝐄𝐈 𝐈𝐎𝐍𝐈𝐂 𝐁𝐎𝐍𝐃 𝐁𝐀𝐍𝐀 𝐊𝐄 𝐕𝐈𝐑𝐆𝐈𝐍𝐈𝐓𝐘 𝐋𝐎𝐎𝐒𝐄 𝐊𝐀𝐑𝐖𝐀 𝐃𝐔𝐍𝐆𝐀 𝐔𝐒𝐊𝐈 📚 😎🤩", 
    "𝐓𝐄𝐑𝐈 𝐑𝐀𝐍𝐃𝐈 𝐌𝐀𝐀 𝐒𝐄 𝐏𝐔𝐂𝐇𝐍𝐀 𝐁𝐀𝐀𝐏 𝐊𝐀 𝐍𝐀𝐀𝐌 𝐁𝐀𝐇𝐄𝐍 𝐊𝐄 𝐋𝐎𝐃𝐄𝐄𝐄𝐄𝐄 🤩🥳😳", 
    "𝐓𝐔 𝐀𝐔𝐑 𝐓𝐄𝐑𝐈 𝐌𝐀𝐀 𝐃𝐎𝐍𝐎 𝐊𝐈 𝐁𝐇𝐎𝐒𝐃𝐄 𝐌𝐄𝐈 𝐌𝐄𝐓𝐑𝐎 𝐂𝐇𝐀𝐋𝐖𝐀 𝐃𝐔𝐍𝐆𝐀 𝐌𝐀𝐃𝐀𝐑𝐗𝐇𝐎𝐃 🚇🤩😱🥶", 
    "𝐓𝐄𝐑𝐈 𝐌𝐀𝐀 𝐊𝐎 𝐈𝐓𝐍𝐀 𝐂𝐇𝐎𝐃𝐔𝐍𝐆𝐀 𝐓𝐄𝐑𝐀 𝐁𝐀𝐀𝐏 𝐁𝐇𝐈 𝐔𝐒𝐊𝐎 𝐏𝐀𝐇𝐂𝐇𝐀𝐍𝐀𝐍𝐄 𝐒𝐄 𝐌𝐀𝐍𝐀 𝐊𝐀𝐑 𝐃𝐄𝐆𝐀😂👿🤩", 
    "𝐓𝐄𝐑𝐈 𝐁𝐀𝐇𝐄𝐍 𝐊𝐄 𝐁𝐇𝐎𝐒𝐃𝐄 𝐌𝐄𝐈 𝐇𝐀𝐈𝐑 𝐃𝐑𝐘𝐄𝐑 𝐂𝐇𝐀𝐋𝐀 𝐃𝐔𝐍𝐆𝐀𝐀💥🔥🔥", 
    "𝐓𝐄𝐑𝐈 𝐌𝐀𝐀 𝐊𝐈 𝐂𝐇𝐔𝐓 𝐌𝐄𝐈 𝐓𝐄𝐋𝐄𝐆𝐑𝐀𝐌 𝐊𝐈 𝐒𝐀𝐑𝐈 𝐑𝐀𝐍𝐃𝐈𝐘𝐎𝐍 𝐊𝐀 𝐑𝐀𝐍𝐃𝐈 𝐊𝐇𝐀𝐍𝐀 𝐊𝐇𝐎𝐋 𝐃𝐔𝐍𝐆𝐀𝐀👿🤮😎", 
    "𝐓𝐄𝐑𝐈 𝐌𝐀𝐀 𝐊𝐈 𝐂𝐇𝐔𝐓 𝐀𝐋𝐄𝐗𝐀 𝐃𝐀𝐋 𝐊𝐄𝐄 𝐃𝐉 𝐁𝐀𝐉𝐀𝐔𝐍𝐆𝐀𝐀𝐀 🎶 ⬆️🤩💥", 
    "𝐓𝐄𝐑𝐈 𝐌𝐀𝐀 𝐊𝐄 𝐁𝐇𝐎𝐒𝐃𝐄 𝐌𝐄𝐈 𝐆𝐈𝐓𝐇𝐔𝐁 𝐃𝐀𝐋 𝐊𝐄 𝐀𝐏𝐍𝐀 𝐁𝐎𝐓 𝐇𝐎𝐒𝐓 𝐊𝐀𝐑𝐔𝐍𝐆𝐀𝐀 🤩👊👤😍", 
    "𝐓𝐄𝐑𝐈 𝐁𝐀𝐇𝐄𝐍 𝐊𝐀 𝐕𝐏𝐒 𝐁𝐀𝐍𝐀 𝐊𝐄 𝟐𝟒*𝟕 𝐁𝐀𝐒𝐇 𝐂𝐇𝐔𝐃𝐀𝐈 𝐂𝐎𝐌𝐌𝐀𝐍𝐃 𝐃𝐄 𝐃𝐔𝐍𝐆𝐀𝐀 🤩💥🔥🔥", 
    "𝐓𝐄𝐑𝐈 𝐌𝐔𝐌𝐌𝐘 𝐊𝐈 𝐂𝐇𝐔𝐓 𝐌𝐄𝐈 𝐓𝐄𝐑𝐄 𝐋𝐀𝐍𝐃 𝐊𝐎 𝐃𝐀𝐋 𝐊𝐄 𝐊𝐀𝐀𝐓 𝐃𝐔𝐍𝐆𝐀 𝐌𝐀𝐃𝐀𝐑𝐂𝐇𝐎𝐃 🔪😂🔥", 
    "𝐒𝐔𝐍 𝐓𝐄𝐑𝐈 𝐌𝐀𝐀 𝐊𝐀 𝐁𝐇𝐎𝐒𝐃𝐀 𝐀𝐔𝐑 𝐓𝐄𝐑𝐈 𝐁𝐀𝐇𝐄𝐍 𝐊𝐀 𝐁𝐇𝐈 𝐁𝐇𝐎𝐒𝐃𝐀 👿😎👊", 
    "𝐓𝐔𝐉𝐇𝐄 𝐃𝐄𝐊𝐇 𝐊𝐄 𝐓𝐄𝐑𝐈 𝐑𝐀𝐍𝐃𝐈 𝐁𝐀𝐇𝐄𝐍 𝐏𝐄 𝐓𝐀𝐑𝐀𝐒 𝐀𝐓𝐀 𝐇𝐀𝐈 𝐌𝐔𝐉𝐇𝐄 𝐁𝐀𝐇𝐄𝐍 𝐊𝐄 𝐋𝐎𝐃𝐄𝐄𝐄𝐄 👿💥🤩🔥", 
    "𝐒𝐔𝐍 𝐌𝐀𝐃𝐀𝐑𝐂𝐇𝐎𝐃 𝐉𝐘𝐀𝐃𝐀 𝐍𝐀 𝐔𝐂𝐇𝐀𝐋 𝐌𝐀𝐀 𝐂𝐇𝐎𝐃 𝐃𝐄𝐍𝐆𝐄 𝐄𝐊 𝐌𝐈𝐍 𝐌𝐄𝐈 ✅🤣🔥🤩", 
    "𝐀𝐏𝐍𝐈 𝐀𝐌𝐌𝐀 𝐒𝐄 𝐏𝐔𝐂𝐇𝐍𝐀 𝐔𝐒𝐊𝐎 𝐔𝐒 𝐊𝐀𝐀𝐋𝐈 𝐑𝐀𝐀𝐓 𝐌𝐄𝐈 𝐊𝐀𝐔𝐍 𝐂𝐇𝐎𝐃𝐍𝐄𝐄 𝐀𝐘𝐀 𝐓𝐇𝐀𝐀𝐀! 𝐓𝐄𝐑𝐄 𝐈𝐒 𝐏𝐀𝐏𝐀 𝐊𝐀 𝐍𝐀𝐀𝐌 𝐋𝐄𝐆𝐈 😂👿😳", 
    "𝐓𝐎𝐇𝐀𝐑 𝐁𝐀𝐇𝐈𝐍 𝐂𝐇𝐎𝐃𝐔 𝐁𝐁𝐀𝐇𝐄𝐍 𝐊𝐄 𝐋𝐀𝐖𝐃𝐄 𝐔𝐒𝐌𝐄 𝐌𝐈𝐓𝐓𝐈 𝐃𝐀𝐋 𝐊𝐄 𝐂𝐄𝐌𝐄𝐍𝐓 𝐒𝐄 𝐁𝐇𝐀𝐑 𝐃𝐔 🏠🤢🤩💥", 
    "𝐓𝐔𝐉𝐇𝐄 𝐀𝐁 𝐓𝐀𝐊 𝐍𝐀𝐇𝐈 𝐒𝐌𝐉𝐇 𝐀𝐘𝐀 𝐊𝐈 𝐌𝐀𝐈 𝐇𝐈 𝐇𝐔 𝐓𝐔𝐉𝐇𝐄 𝐏𝐀𝐈𝐃𝐀 𝐊𝐀𝐑𝐍𝐄 𝐖𝐀𝐋𝐀 𝐁𝐇𝐎𝐒𝐃𝐈𝐊𝐄𝐄 𝐀𝐏𝐍𝐈 𝐌𝐀𝐀 𝐒𝐄 𝐏𝐔𝐂𝐇 𝐑𝐀𝐍𝐃𝐈 𝐊𝐄 𝐁𝐀𝐂𝐇𝐄𝐄𝐄𝐄 🤩👊👤😍", 
    "𝐓𝐄𝐑𝐈 𝐌𝐀𝐀 𝐊𝐄 𝐁𝐇𝐎𝐒𝐃𝐄 𝐌𝐄𝐈 𝐒𝐏𝐎𝐓𝐈𝐅𝐘 𝐃𝐀𝐋 𝐊𝐄 𝐋𝐎𝐅𝐈 𝐁𝐀𝐉𝐀𝐔𝐍𝐆𝐀 𝐃𝐈𝐍 𝐁𝐇𝐀𝐑 😍🎶🎶💥", 
    "𝐓𝐄𝐑𝐈 𝐌𝐀𝐀 𝐊𝐀 𝐍𝐀𝐘𝐀 𝐑𝐀𝐍𝐃𝐈 𝐊𝐇𝐀𝐍𝐀 𝐊𝐇𝐎𝐋𝐔𝐍𝐆𝐀 𝐂𝐇𝐈𝐍𝐓𝐀 𝐌𝐀𝐓 𝐊𝐀𝐑 👊🤣🤣😳", 
    "𝐓𝐄𝐑𝐀 𝐁𝐀𝐀𝐏 𝐇𝐔 𝐁𝐇𝐎𝐒𝐃𝐈𝐊𝐄 𝐓𝐄𝐑𝐈 𝐌𝐀𝐀 𝐊𝐎 𝐑𝐀𝐍𝐃𝐈 𝐊𝐇𝐀𝐍𝐄 𝐏𝐄 𝐂𝐇𝐔𝐃𝐖𝐀 𝐊𝐄 𝐔𝐒 𝐏𝐀𝐈𝐒𝐄 𝐊𝐈 𝐃𝐀𝐀𝐑𝐔 𝐏𝐄𝐄𝐓𝐀 𝐇𝐔 🍷🤩🔥", 
    "𝐓𝐄𝐑𝐈 𝐁𝐀𝐇𝐄𝐍 𝐊𝐈 𝐂𝐇𝐔𝐓 𝐌𝐄𝐈 𝐀𝐏𝐍𝐀 𝐁𝐀𝐃𝐀 𝐒𝐀 𝐋𝐎𝐃𝐀 𝐆𝐇𝐔𝐒𝐒𝐀 𝐃𝐔𝐍𝐆𝐀𝐀 𝐊𝐀𝐋𝐋𝐀𝐀𝐏 𝐊𝐄 𝐌𝐀𝐑 𝐉𝐀𝐘𝐄𝐆𝐈 🤩😳😳🔥", 
    "𝐓𝐎𝐇𝐀𝐑 𝐌𝐔𝐌𝐌𝐘 𝐊𝐈 𝐂𝐇𝐔𝐓 𝐌𝐄𝐈 𝐏𝐔𝐑𝐈 𝐊𝐈 𝐏𝐔𝐑𝐈 𝐊𝐈𝐍𝐆𝐅𝐈𝐒𝐇𝐄𝐑 𝐊𝐈 𝐁𝐎𝐓𝐓𝐋𝐄 𝐃𝐀𝐋 𝐊𝐄 𝐓𝐎𝐃 𝐃𝐔𝐍𝐆𝐀 𝐀𝐍𝐃𝐄𝐑 𝐇𝐈 😱😂🤩", 
    "𝐓𝐄𝐑𝐈 𝐌𝐀𝐀 𝐊𝐎 𝐈𝐓𝐍𝐀 𝐂𝐇𝐎𝐃𝐔𝐍𝐆𝐀 𝐊𝐈 𝐒𝐀𝐏𝐍𝐄 𝐌𝐄𝐈 𝐁𝐇𝐈 𝐌𝐄𝐑𝐈 𝐂𝐇𝐔𝐃𝐀𝐈 𝐘𝐀𝐀𝐃 𝐊𝐀𝐑𝐄𝐆𝐈 𝐑𝐀𝐍𝐃𝐈 🥳😍👊💥", 
    "𝐓𝐄𝐑𝐈 𝐌𝐔𝐌𝐌𝐘 𝐀𝐔𝐑 𝐁𝐀𝐇𝐄𝐍 𝐊𝐎 𝐃𝐀𝐔𝐃𝐀 𝐃𝐀𝐔𝐃𝐀 𝐍𝐄 𝐂𝐇𝐎𝐃𝐔𝐍𝐆𝐀 𝐔𝐍𝐊𝐄 𝐍𝐎 𝐁𝐎𝐋𝐍𝐄 𝐏𝐄 𝐁𝐇𝐈 𝐋𝐀𝐍𝐃 𝐆𝐇𝐔𝐒𝐀 𝐃𝐔𝐍𝐆𝐀 𝐀𝐍𝐃𝐄𝐑 𝐓𝐀𝐊 😎😎🤣🔥", 
    "𝐓𝐄𝐑𝐈 𝐌𝐔𝐌𝐌𝐘 𝐊𝐈 𝐂𝐇𝐔𝐓 𝐊𝐎 𝐎𝐍𝐋𝐈𝐍𝐄 𝐎𝐋𝐗 𝐏𝐄 𝐁𝐄𝐂𝐇𝐔𝐍𝐆𝐀 𝐀𝐔𝐑 𝐏𝐀𝐈𝐒𝐄 𝐒𝐄 𝐓𝐄𝐑𝐈 𝐁𝐀𝐇𝐄𝐍 𝐊𝐀 𝐊𝐎𝐓𝐇𝐀 𝐊𝐇𝐎𝐋 𝐃𝐔𝐍𝐆𝐀 😎🤩😝😍", 
    "𝐓𝐄𝐑𝐈 𝐌𝐀𝐀 𝐊𝐄 𝐁𝐇𝐎𝐒𝐃𝐀 𝐈𝐓𝐍𝐀 𝐂𝐇𝐎𝐃𝐔𝐍𝐆𝐀 𝐊𝐈 𝐓𝐔 𝐂𝐀𝐇 𝐊𝐄 𝐁𝐇𝐈 𝐖𝐎 𝐌𝐀𝐒𝐓 𝐂𝐇𝐔𝐃𝐀𝐈 𝐒𝐄 𝐃𝐔𝐑 𝐍𝐇𝐈 𝐉𝐀 𝐏𝐀𝐘𝐄𝐆𝐀𝐀 😏😏🤩😍", 
    "𝐒𝐔𝐍 𝐁𝐄 𝐑𝐀𝐍𝐃𝐈 𝐊𝐈 𝐀𝐔𝐋𝐀𝐀𝐃 𝐓𝐔 𝐀𝐏𝐍𝐈 𝐁𝐀𝐇𝐄𝐍 𝐒𝐄 𝐒𝐄𝐄𝐊𝐇 𝐊𝐔𝐂𝐇 𝐊𝐀𝐈𝐒𝐄 𝐆𝐀𝐀𝐍𝐃 𝐌𝐀𝐑𝐖𝐀𝐓𝐄 𝐇𝐀𝐈😏🤬🔥💥", 
    "𝐓𝐄𝐑𝐈 𝐌𝐀𝐀 𝐊𝐀 𝐘𝐀𝐀𝐑 𝐇𝐔 𝐌𝐄𝐈 𝐀𝐔𝐑 𝐓𝐄𝐑𝐈 𝐁𝐀𝐇𝐄𝐍 𝐊𝐀 𝐏𝐘𝐀𝐀𝐑 𝐇𝐔 𝐌𝐄𝐈 𝐀𝐉𝐀 𝐌𝐄𝐑𝐀 𝐋𝐀𝐍𝐃 𝐂𝐇𝐎𝐎𝐒 𝐋𝐄 🤩🤣💥", 
    "𝐌𝐀𝐃𝐀𝐑𝐂𝐇𝐎𝐃",
    "BHOSDIKE",
    "LAAAWEEE KE BAAAAAL",
    "MAAAAR KI JHAAAAT KE BBBBBAAAAALLLLL",
    "MADRCHOD..",
    "TERI MA KI CHUT..",
    "LWDE KE BAAALLL.",
    "MACHAR KI JHAAT KE BAAALLLL",
    "TERI MA KI CHUT M DU TAPA TAP?",
    "TERI MA KA BHOSDAA",
    "TERI BHN SBSBE BDI RANDI.",
    "TERI MA OSSE BADI RANDDDDD",
    "TERA BAAP CHKAAAA",
    "KITNI CHODU TERI MA AB OR..",
    "TERI MA CHOD DI HM NE",
    "TERI MA KE STH REELS BNEGA ROAD PEE",
    "TERI MA KI CHUT EK DAM TOP SEXY",
    "MALUM NA PHR KESE LETA HU M TERI MA KI CHUT TAPA TAPPPPP",
    "LUND KE CHODE TU KEREGA TYPIN",
    "SPEED PKD LWDEEEE",
    "BAAP KI SPEED MTCH KRRR",
    "LWDEEE",
    "PAPA KI SPEED MTCH NHI HO RHI KYA",
    "ALE ALE MELA BCHAAAA",
    "CHUD GYA PAPA SEEE",
    "KISAN KO KHODNA OR",
    "SALE RAPEKL KRDKA TERA",
    "HAHAHAAAAA",
    "KIDSSSS",
    "TERI MA CHUD GYI AB FRAR MT HONA",
    "YE LDNGE BAPP SE",
    "KIDSSS FRAR HAHAHH",
    "BHEN KE LWDE SHRM KR",
    "KITNI GLIYA PDWEGA APNI MA KO",
    "NALLEE",
    "SHRM KR",
    "MERE LUND KE BAAAAALLLLL",
    "KITNI GLIYA PDWYGA APNI MA BHEN KO",
    "RNDI KE LDKEEEEEEEEE",
    "KIDSSSSSSSSSSSS",
    "Apni gaand mein muthi daal",
    "Apni lund choos",
    "Apni ma ko ja choos",
    "Bhen ke laude",
    "Bhen ke takke",
    "Abla TERA KHAN DAN CHODNE KI BARIII",
    "BETE TERI MA SBSE BDI RAND",
    "LUND KE BAAAL JHAT KE PISSSUUUUUUU",
    "LUND PE LTKIT MAAALLLL KI BOND H TUUU",
    "KASH OS DIN MUTH MRKE SOJTA M TUN PAIDA NA HOTAA",
    "GLTI KRDI TUJW PAIDA KRKE",
    "SPEED PKDDD",
    "Gaand main LWDA DAL LE APNI MERAAA",
    "Gaand mein bambu DEDUNGAAAAAA",
    "GAND FTI KE BALKKK",
    "Gote kitne bhi bade ho, lund ke niche hi rehte hai",
    "Hazaar lund teri gaand main",
    "Jhaant ke pissu-",
    "TERI MA KI KALI CHUT",
    "Khotey ki aulda",
    "Kutte ka awlat",
    "Kutte ki jat",
    "Kutte ke tatte",
    "TETI MA KI.CHUT , tERI MA RNDIIIIIIIIIIIIIIIIIIII",
    "Lavde ke bal",
    "muh mei lele",
    "Lund Ke Pasine",
    "MERE LWDE KE BAAAAALLL",
    "HAHAHAAAAAA",
    "CHUD GYAAAAA",
    "Randi khanE KI ULADDD",
    "Sadi hui gaand",
    "Teri gaand main kute ka lund",
    "Teri maa ka bhosda",
    "Teri maa ki chut",
    "Tere gaand mein keede paday",
    "Ullu ke pathe",
    "SUNN MADERCHOD",
    "TERI MAA KA BHOSDA",
    "BEHEN K LUND",
    "TERI MAA KA CHUT KI CHTNIIII",
    "MERA LAWDA LELE TU AGAR CHAIYE TOH",
    "GAANDU",
    "CHUTIYA",
    "TERI MAA KI CHUT PE JCB CHADHAA DUNGA",
    "SAMJHAA LAWDE",
    "YA DU TERE GAAND ME TAPAA TAP��",
    "TERI BEHEN MERA ROZ LETI HAI",
    "TERI GF K SAATH MMS BANAA CHUKA HU���不�不",
    "TU CHUTIYA TERA KHANDAAN CHUTIYA",
    "AUR KITNA BOLU BEY MANN BHAR GAYA MERA�不",
    "TERIIIIII MAAAA KI CHUTTT ME ABCD LIKH DUNGA MAA KE LODE",
    "TERI MAA KO LEKAR MAI FARAR",
    "RANIDIII",
    "BACHEE",
    "CHODU",
    "RANDI",
    "RANDI KE PILLE",
    "TERIIIII MAAA KO BHEJJJ",
    "TERAA BAAAAP HU",
    "teri MAA KI CHUT ME HAAT DAALLKE BHAAG JAANUGA",
    "Teri maa KO SARAK PE LETAA DUNGA",
    "TERI MAA KO GB ROAD PE LEJAKE BECH DUNGA",
    "Teri maa KI CHUT MÉ KAALI MITCH",
    "TERI MAA SASTI RANDI HAI",
    "TERI MAA KI CHUT ME KABUTAR DAAL KE SOUP BANAUNGA MADARCHOD",
    "TERI MAAA RANDI HAI",
    "TERI MAAA KI CHUT ME DETOL DAAL DUNGA MADARCHOD",
    "TERI MAA KAAA BHOSDAA",
    "TERI MAA KI CHUT ME LAPTOP",
    "Teri maa RANDI HAI",
    "TERI MAA KO BISTAR PE LETAAKE CHODUNGA",
    "TERI MAA KO AMERICA GHUMAAUNGA MADARCHOD",
    "TERI MAA KI CHUT ME NAARIYAL PHOR DUNGA",
    "TERI MAA KE GAND ME DETOL DAAL DUNGA",
    "TERI MAAA KO HORLICKS PILAUNGA MADARCHOD",
    "TERI MAA KO SARAK PE LETAAA DUNGAAA",
    "TERI MAA KAA BHOSDA",
    "MERAAA LUND PAKAD LE MADARCHOD",
    "CHUP TERI MAA AKAA BHOSDAA",
    "TERIII MAA CHUF GEYII KYAAA LAWDEEE",
    "TERIII MAA KAA BJSODAAA",
    "MADARXHODDD",
    "TERIUUI MAAA KAA BHSODAAA",
    "TERIIIIII BEHENNNN KO CHODDDUUUU MADARXHODDDD",
    "NIKAL MADARCHOD",
    "RANDI KE BACHE",
    "TERA MAA MERI FAN",
    "TERI SEXY BAHEN KI CHUT OP",
]
GRP = "@THE_DRAMA_CLUB_01|@ll_BAD_ABOUT_ll|@ll_BAD_MUNDA_WORLD_ll"

GROUP = [-1002056907061]

VERIFIED_USERS = [6566179661, 6898413162]

Owners = "@PbxBad"
